global:
  gateway:
    name: '{{ .toptin.aws-alb.global.externalGateway | .toptin.google-gateway.global.externalGateway | .toptin.azure-gateway.global.externalGateway | required }}'
    namespace: '{{ .toptmodule.aws-alb | .toptmodule.google-gateway | .toptmodule.azure-gateway | required }}'
