google:
  externalCertificateMap: ""
  internalCertificateMap: ""
  externalGatewayClassName: gke-l7-global-external-managed
  internalGatewayClassName: gke-l7-global-external-managed

createExternal: true
createInternal: true
