global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
    region: "{{ .toutput.eks.region }}"
    kmsKeyId: "{{ .toptout.kms.data_alias_arn }}"
  bucketName: "{{ .config.prefix }}-{{ .module.name }}-metrics"
mimir-distributed:
  gateway:
    ingress:
      hosts:
      - host: "{{ .module.name }}.{{ .toutput.route53.int_domain }}"
        paths:
        - path: "/"
          pathType: "Prefix"
