global:
  bucketName: "{{ .config.prefix }}-{{ .tsmodule.mimir }}-metrics"
  google:
    hostname: "{{ .tsmodule.mimir }}.{{ .toutput.dns.int_domain }}"
    projectID: "{{ .toutput.crossplane.project_id }}"
    gateway:
      name: google-gateway-internal
      namespace: google-gateway
    bucket:
      location: "{{ .toutput.gke.region }}"
