global:
  bucketName: "{{ .config.prefix }}-{{ .module.name }}-metrics"
  azure:
    subscriptionId: "{{ .agent.accountId }}"
    resourceGroupName: "{{ .agent.resourceGroup }}"
    location: "{{ .agent.region }}"
    storageAccountPrefix: "{{ .config.prefix }}{{ .module.name }}"
    uniqueSuffix: "{{ .agent.uniqueSuffix }}"
    telemetryKeyId: "{{ .toptout.kms.telemetry_key_id }}"
    telemetryKeyResourceId: "{{ .toptout.kms.telemetry_key_resource_id }}"
    identityPrefix: "{{ .toutput.aks.cluster_name }}"
