apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: external-secrets  
spec:
  forProvider:
    name: external-secrets
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "secretsmanager:GetResourcePolicy",
              "secretsmanager:GetSecretValue",
              "secretsmanager:DescribeSecret",
              "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": [
              "arn:aws:secretsmanager:eu-north-1:{{ .Values.awsAccount }}:secret:*"
            ]
          }
        ]
      }

  providerConfigRef:
    name: aws-crossplane
