apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: secret-manager-operator
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::{{ .Values.awsAccount }}:oidc-provider/oidc.eks.eu-north-1.amazonaws.com/id/{{ .Values.clusterOIDC }}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "oidc.eks.eu-north-1.amazonaws.com/id/{{ .Values.clusterOIDC }}:aud": "sts.amazonaws.com",
                "oidc.eks.eu-north-1.amazonaws.com/id/{{ .Values.clusterOIDC }}:sub": "system:serviceaccount:external-secrets:secret-manager-operator"
              }
            }
          }
        ]
      }
  providerConfigRef:
    name: aws-crossplane
