{{- if eq .Values.cloudProvider "google" }}

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Name }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{ .Values.google.gateway.name }}
      sectionName: https
      namespace: {{ .Values.google.gateway.namespace }}
  hostnames:
    - {{ .Values.argocd.global.domain }}
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}-server
          port: 443
        
{{- end }}