global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
cluster-autoscaler:
  awsRegion: "{{ .toutput.eks.region }}"
  autoDiscovery:
    clusterName: "{{ .toutput.eks.cluster_name }}"
