apiVersion: v2
name: cluster-autoscaler
description: cluster-autoscaler
version: 0.1.0
appVersion: "0.1.0"

dependencies:
- name: cluster-autoscaler
  version: 9.40.0
  repository: https://kubernetes.github.io/autoscaler

