apiVersion: v2
name: cluster-autoscaler
description: cluster-autoscaler
version: 9.43.2
appVersion: "9.43.2"

dependencies:
- name: cluster-autoscaler
  version: 9.43.2
  repository: https://kubernetes.github.io/autoscaler

