{{- if and (eq .Values.cloudProvider "google") .Values.addMembers }}

apiVersion: dns.gcp.upbound.io/v1beta1
kind: ManagedZoneIAMMember
metadata:
  name: managed-zone-iam-member-dns-admin
spec:
  forProvider:
    managedZone: {{ .Values.managedZone }}
    member: serviceAccount:{{.Values.projectID }}.svc.id.goog[{{ .Values.kubernetesNamespace }}/{{ .Values.kubernetesServiceAccount }}]
    role: roles/dns.admin
  providerConfigRef:
    name: workload-id-providerconfig

{{- end }}
