{{- if eq .Values.cloudProvider "google" }}

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ .Release.Name }}
spec:
  forProvider:
    member: serviceAccount:{{ .Values.projectID }}.svc.id.goog[{{ .Release.Name }}/external-dns]
    project: {{ .Values.projectID }}
    role: roles/dns.admin
  providerConfigRef:
    name: workload-id-providerconfig

{{- end }}
