{{- if and (eq .Values.cloudProvider "google") .Values.createMembers }}

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: project-iam-member-dns-reader
spec:
  forProvider:
    member: serviceAccount:{{.Values.projectID }}.svc.id.goog[{{ .Values.kubernetesNamespace }}/{{ .Values.kubernetesServiceAccount }}]
    project: {{ .Values.projectID }}
    role: roles/dns.reader
  providerConfigRef:
    name: workload-id-providerconfig

{{- end }}
