global:
  google:
    projectID: "{{ .toutput.crossplane.project_id }}"
    hostname: "{{ .module.name }}.{{ .toutput.dns.int_domain }}"
    gateway:
      name: google-gateway-internal
      namespace: google-gateway
  loki:
    hostname: "{{ .toptout.loki.loki_hostname }}"
  prometheus:
    hostname: "{{ .toptout.prometheus.prometheus_hostname }}"
grafana:
  grafana.ini:
    server:
      root_url: https://{{ .module.name }}.{{ .toutput.dns.int_domain }}
  serviceAccount:
    name: "{{ .module.name }}"