global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
    region: "{{ .toutput.eks.region }}"
  datasources:
    loki:
      hostname: "http://loki-gateway.{{ .tmodule.loki }}"
    prometheus:
      hostname: "http://{{ .tmodule.prometheus }}-server.{{ .tmodule.prometheus }}"

grafana:
  grafana.ini:
    server:
      root_url: https://{{ .module.name }}.{{ .toutput.route53.int_domain }}
  ingress:
    hosts:
      - "{{ .module.name }}.{{ .toutput.route53.int_domain }}"
