global:
  datasources:
    loki:
      hostname: "{{ .toptout.loki.loki_hostname }}"
    prometheus:
      hostname: "{{ .toptout.prometheus.prometheus_hostname }}"
grafana:
  grafana.ini:
    server:
      root_url: https://grafana.{{ .toutput.dns.int_domain }}
  ingress:
    hosts:
    - grafana.{{ .toutput.dns.int_domain }}
