global:
  google:
    projectID: "{{ .toutput.crossplane.project_id }}"
    hostname: grafana.{{ .toutput.dns.int_domain }}
    gateway:
      name: google-gateway-internal
      namespace: google-gateway
grafana:
  grafana.ini:
    server:
      root_url: https://grafana.{{ .toutput.dns.int_domain }}
