global:
  azure:
    subscriptionId: "{{ .toutput.crossplane.subscription_id }}"
    resourceGroupId: "/subscriptions/{{ .agent.accountId }}/resourceGroups/{{ .agent.resourceGroup }}"
    nodeResourceGroupId: "{{ .toutput.aks.node_resource_group_id }}"
  datasources:
    loki:
      module: "{{ .toptmodule.loki }}"
