global:
  datasources:
    loki:
      hostname: "{{ .toptout.loki.hostname }}"
    prometheus:
      hostname: "{{ .toptout.prometheus.hostname }}"
grafana:
  grafana.ini:
    server:
      root_url: https://grafana.{{ .toutput.route53.int_domain }}
  ingress:
    hosts:
    - grafana.{{ .toutput.route53.int_domain }}
