apiVersion: v2
name: grafana
description: A umbrella chart for Grafana
type: application
version: 0.2.0
appVersion: "7.0.11"

dependencies:
- name: grafana
  version: 7.0.11
  repository: https://grafana.github.io/helm-charts
