global:
  cloudProvider: "google"
  providerConfigRefName: "crossplane-google"

  google:
    projectID: ""
    hostname: ""
    gateway:
      name: google-gateway-external
      namespace: google-gateway

grafana:
  ingress:
    enabled: false
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 2Gi
  serviceAccount:
    create: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus-{{ .Values.global.google.projectID }}
          type: prometheus
          url: http://prometheus-server.prometheus
          access: proxy
          isDefault: true
        - name: Loki-{{ .Values.global.google.projectID }}
          type: loki
          access: proxy
          url: http://loki-gateway.loki
          jsonData:
            maxLines: 1000
        - name: Google Cloud Monitoring
          type: stackdriver
          access: proxy
          jsonData:
            authenticationType: gce

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "kubernetes"
          orgId: 1
          folder: "Kubernetes"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/kubernetes
        - name: "loki"
          orgId: 1
          folder: "Loki"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/loki

  dashboardsConfigMaps:
    loki: grafana-dashboards-loki
