global:
  cloudProvider: "google"
  providerConfigRefName: "crossplane-google"

  google:
    projectID: ""
    hostname: ""
    gateway:
      name: google-gateway-external
      namespace: google-gateway

grafana:
  ingress:
    enabled: false
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 2Gi
  serviceAccount:
    create: false

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "kubernetes"
          orgId: 1
          folder: "Kubernetes"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/kubernetes
        - name: "loki"
          orgId: 1
          folder: "Loki"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/loki

  dashboardsConfigMaps:
    loki: grafana-dashboards-loki
