global:
  cloudProvider: "aws"
  providerConfigRefName: "crossplane-aws"

  aws:
    account: ""
    clusterOIDC: ""

grafana:
  serviceAccount:
    create: false

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "kubernetes"
          orgId: 1
          folder: "Kubernetes"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/kubernetes
        - name: "loki"
          orgId: 1
          folder: "Loki"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/loki

  dashboardsConfigMaps:
    loki: grafana-dashboards-loki
