cloudProvider: "google"

google:
  hostname: ""
  gateway:
    name: gcp-gateway-external
    namespace: gcp-gateway

grafana:
  ingress:
    enabled: false
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 2Gi
