cloudProvider: "google"

google:
  hostname: ""
  gateway:
    name: google-gateway-external
    namespace: google-gateway

grafana:
  ingress:
    enabled: false
  persistence:
    enabled: true
    storageClassName: "standard"
    size: 2Gi
