{{ if not (eq .Values.gitlab_secet "") }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  labels: 
    type: gitlab
type: Opaque 
stringData:
  token: {{ .Values.gitlab_secet }}
{{ end }}
