{{ if not (eq .Values.global.gitlab.secret "") }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
  labels: 
    type: gitlab
type: Opaque 
stringData:
  token: {{ .Values.global.gitlab.secret }}
{{ end }}
