{
 "title": "AWS EBS",
 "description": "Visualize AWS EBS metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Account", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "volumeid",
    "label": "VolumeId",
    "query": "dimension_values($region, AWS/EBS, VolumeQueueLength, VolumeId)"
   }
  ]
 },
 "panels": [
  {
   "title": "VolumeQueueLength",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeQueueLength",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "VolumeTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeTotalReadTime",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeTotalWriteTime",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeIdleTime",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "VolumeThroughputPercentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeThroughputPercentage",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeConsumedReadWriteOps",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "VolumeReadBytes/VolumeWriteBytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeReadBytes",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeWriteBytes",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "VolumeReadOps/VolumeWriteOps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeReadOps",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "VolumeWriteOps",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "BurstBalance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "VolumeId": "$volumeid" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BurstBalance",
     "namespace": "AWS/EBS",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using_cloudwatch_ebs.html\">AWS Cloudwatch EBS documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/623\">Installed from Grafana.com dashboards</a>"
   },
   "targets": [
    {}
   ]
  }
 ]
}