{
 "title": "AWS Transit Gateway",
 "description": "Visualize AWS Transit Gateway metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "transitgateway",
    "label": "TransitGateway",
    "query": "dimension_values($region, AWS/TransitGateway, BytesIn, TransitGateway)"
   },
   {
    "name": "transitgatewayattachment",
    "label": "TransitGatewayAttachment",
    "query": "dimension_values($region, AWS/TransitGateway, BytesIn, TransitGatewayAttachment)"
   }
  ]
 },
 "panels": [
  {
   "title": "BytesIn / BytesOut",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "TransitGateway": "$transitgateway" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesIn",
     "namespace": "AWS/TransitGateway",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "TransitGateway": "$transitgateway" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesOut",
     "namespace": "AWS/TransitGateway",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PacketsIn / PacketsOut",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TransitGateway": "$transitgateway" },
     "metricName": "PacketsOut",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "TransitGateway": "$transitgateway" },
     "metricName": "PacketsIn",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PacketDropCountNoRoute / PacketDropCountBlackhole",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TransitGateway": "$transitgateway" },
     "metricName": "PacketDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "TransitGateway": "$transitgateway" },
     "metricName": "PacketDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesDropCountNoRoute / BytesDropCountBlackhole",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "TransitGateway": "$transitgateway" },
     "metricName": "BytesDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": { "TransitGateway": "$transitgateway" },
     "metricName": "BytesDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesIn / BytesOut  for $transitgatewayattachment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": {
      "TransitGateway": "$transitgateway",
      "TransitGatewayAttachment": "$transitgatewayattachment"
     },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesIn",
     "namespace": "AWS/TransitGateway",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": {
      "TransitGateway": "$transitgateway",
      "TransitGatewayAttachment": "$transitgatewayattachment"
     },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesOut",
     "namespace": "AWS/TransitGateway",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PacketsIn / PacketsOut for $transitgatewayattachment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "TransitGateway": "$transitgateway",
      "TransitGatewayAttachment": "$transitgatewayattachment"
     },
     "metricName": "PacketsOut",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "TransitGateway": "$transitgateway",
      "TransitGatewayAttachment": "$transitgatewayattachment"
     },
     "metricName": "PacketsIn",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PacketDropCountNoRoute / PacketDropCountBlackhole for $transitgatewayattachment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "TransitGateway": "$transitgateway",
      "TransitGatewayAttachment": "$transitgatewayattachment"
     },
     "metricName": "PacketDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "TransitGateway": "$transitgateway",
      "TransitGatewayAttachment": "$transitgatewayattachment"
     },
     "metricName": "PacketDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesDropCountNoRoute / BytesDropCountBlackhole for $transitgatewayattachment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": {
      "TransitGateway": "$transitgateway",
      "TransitGatewayAttachment": "$transitgatewayattachment"
     },
     "metricName": "BytesDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "dimensions": {
      "TransitGateway": "$transitgateway",
      "TransitGatewayAttachment": "$transitgatewayattachment"
     },
     "metricName": "BytesDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-cloudwatch-metrics.html\">AWS CloudWatch Transit Gateway documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/14954\">Installed from Grafana.com dashboards</a>"
   },
   "targets": [
    {}
   ]
  }
 ]
}