{
 "title": "Amazon RDS OS Metrics",
 "description": "Visualize OS metrics for Amazon RDS instance",
 "tags": [
  "Percona",
  "Cloud "
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Account", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "instance",
    "label": "DB Instance",
    "query": "dimension_values($region,AWS/RDS,CPUUtilization,DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cost",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Cost\n\nAmazon provides 1 million CloudWatch API requests each month at no additional charge. Past this, it costs $0.01 per 1,000 requests. This dashboard does 15 requests on each refresh."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "CPU",
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Credit Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Credits Accumulated",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Credits Accumulated",
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Credits Consumed",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Credits Consumed",
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "period": "300",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Read",
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Write",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Write",
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Read",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Read",
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Write",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Write",
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Outstanding IO Requests",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Outstanding IO Requests",
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Read",
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Write",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Write",
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Available",
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Storage Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Available",
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Used",
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Inbound",
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "Outbound",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "label": "Outbound",
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
     "content": "# Setup\n\nAdd CloudWatch datasource to Grafana with the name `CloudWatch`.\n\nCreate IAM user and attach the managed policy `CloudWatchReadOnlyAccess`. Then put the credentials in the file `~grafana/.aws/credentials`:\n```\n[default]\naws_access_key_id = youraccesskeyid\naws_secret_access_key = yoursecretaccesskey\n```"
    }
   ]
  }
 ]
}