global:
  bucketName: "{{ .config.prefix }}-loki-logs"
  google:
    hostname: loki.{{ .toutput.dns.int_domain }}
    projectID: "{{ .toutput.crossplane.project_id }}"
    gateway:
      name: google-gateway-internal
      namespace: google-gateway
    bucket:
      location: europe-north1
loki:
  loki:
    storage:
      bucketNames:
        admin: "{{ .config.prefix }}-loki-logs"
        chunks: "{{ .config.prefix }}-loki-logs"
        ruler: "{{ .config.prefix }}-loki-logs"
