global:
  bucketName: "{{ .config.prefix }}-{{ .module.name }}-logs"
  azure:
    subscriptionID: "{{ .agent.accountId }}"
    resourceGroupName: "{{ .agent.resourceGroup }}"
    location: "{{ .agent.region }}"
    storageAccountPrefix: "{{ .config.prefix }}{{ .module.name }}"
    uniqueSuffix: "{{ .agent.uniqueSuffix }}"
    telemetryKeyId: "{{ .toptout.kms.telemetry_key_id }}"
    telemetryKeyResourceId: "{{ .toptout.kms.telemetry_key_resource_id }}"
    identityPrefix: "{{ .toutput.aks.cluster_name }}"
    agcSubnetCidrs: "{{ .toutput.vpc.agc_subnet_cidrs }}"
loki:
  loki:
    storage:
      bucketNames:
        admin: "{{ .config.prefix }}-{{ .module.name }}-logs"
        chunks: "{{ .config.prefix }}-{{ .module.name }}-logs"
        ruler: "{{ .config.prefix }}-{{ .module.name }}-logs"
  networkPolicy:
    externalStorage:
      cidrs:
        - "0.0.0.0/0"
    ingress:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: Exists
      podSelector:
        matchExpressions:
          - key: netpol-loki
            operator: In
            values:
              - "loki"
              - "{{ .module.name }}"
