global:
  bucketName: "{{ .config.prefix }}-{{ .tsmodule.loki }}-logs"
  google:
    hostname: "{{ .tsmodule.loki }}.{{ .toutput.dns.int_domain }}"
    projectID: "{{ .toutput.crossplane.project_id }}"
    gateway:
      name: google-gateway-internal
      namespace: google-gateway
    bucket:
      location: "{{ .toutput.gke.region }}"
loki:
  loki:
    storage:
      bucketNames:
        admin: "{{ .config.prefix }}-{{ .tsmodule.loki }}-logs"
        chunks: "{{ .config.prefix }}-{{ .tsmodule.loki }}-logs"
        ruler: "{{ .config.prefix }}-{{ .tsmodule.loki }}-logs"
