global:
  bucketName: "{{ .config.prefix }}-{{ .module.name }}-logs"
  azure:
    storageAccountId: "{{ .toutput.crossplane.agent_storage_account_id }}"
    telemetryKeyId: "{{ .toptout.kms.telemetry_key_id }}"
    agcSubnetCidrs: "{{ .toutput.vpc.agc_subnet_cidrs }}"
loki:
  loki:
    storage:
      azure:
        accountName: "{{ .toutput.crossplane.agent_storage_account_name }}"
      bucketNames:
        admin: "{{ .config.prefix }}-{{ .module.name }}-logs"
        chunks: "{{ .config.prefix }}-{{ .module.name }}-logs"
        ruler: "{{ .config.prefix }}-{{ .module.name }}-logs"
  networkPolicy:
    externalStorage:
      cidrs:
        - "0.0.0.0/0"
    ingress:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: Exists
      podSelector:
        matchExpressions:
          - key: netpol-loki
            operator: In
            values:
              - "loki"
              - "{{ .module.name }}"
