global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
    region: "{{ .toutput.eks.region }}"
    kmsKeyId: "{{ .toptout.kms.data_alias_arn }}"
  bucketName: "{{ .config.prefix }}-{{ .tsmodule.loki }}-logs"
loki:
  gateway:
    ingress:
      hosts:
        - host: "{{ .tsmodule.loki }}.{{ .toutput.route53.int_domain }}"
          paths:
            - path: "/"
              pathType: "Prefix"
  loki:
    storage:
      s3:
        region: "{{ .toutput.eks.region }}"
      bucketNames:
        chunks: "{{ .config.prefix }}-{{ .tsmodule.loki }}-logs"
        ruler: "{{ .config.prefix }}-{{ .tsmodule.loki }}-logs"
        admin: "{{ .config.prefix }}-{{ .tsmodule.loki }}-logs"
    storage_config:
      aws:
        region: "{{ .toutput.eks.region }}"
        bucketnames: "{{ .config.prefix }}-{{ .tsmodule.loki }}-logs"
