spec:
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: loki-read
    jqPathExpressions:
      - .spec.persistentVolumeClaimRetentionPolicy
  - group: identitydomains.oci.upbound.io
    kind: CustomerSecretKey
    name: loki
    jqPathExpressions:
      - .spec.forProvider.ocid
      - .spec.forProvider.user[].ocid
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/warn: restricted
        tenancy.entigo.com/zone: infralib
