{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ .Values.grafana.serviceAccount.name }}
spec:
  forProvider:
    displayName: Grafana Service Account
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
