{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.grafana.serviceAccount.name }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.grafana.serviceAccount.name }}@{{ .Values.global.google.projectID }}.iam.gserviceaccount.com"

{{- end }}
