apiVersion: v2
name: prometheus
description: A Prometheus chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: prometheus
    version: 25.30.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-operator-crds
    version: 18.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: global.installPrometheusOperatorCRDs
  - name: prometheus-blackbox-exporter
    version: 9.2.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: global.installBlackbox
