

prometheus:
  fullnameOverride: prometheus
  server:
    ingress:
      enabled: true
      annotations:
        alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
        { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
        alb.ingress.kubernetes.io/group.name: internal
        alb.ingress.kubernetes.io/healthcheck-path: /
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/success-codes: 200-499
        alb.ingress.kubernetes.io/target-type: ip
        kubernetes.io/ingress.class: alb
      hosts:
        - prometheus
      tls: []
  
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: mon
              operator: In
              values:
              - "true"
        - weight: 10
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "mon"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
        ephemeral-storage: 10Gi
      requests:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 10Mi
  configmapReload:
    prometheus:
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
          ephemeral-storage: 1Gi
        requests:
          cpu: 5m
          memory: 16Mi
          ephemeral-storage: 10Mi
  prometheus-pushgateway:
    enabled: false
  alertmanager:
    enabled: true
    statefulSet:
      annotations: 
        kube-score/ignore: pod-probes,pod-networkpolicy
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: mon
              operator: In
              values:
              - "true"
        - weight: 10
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "mon"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources: 
      limits:
        cpu: 100m
        memory: 1Gi
        ephemeral-storage: 1Gi
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 10Mi    
    networkPolicy:
      enabled: true
      
  kube-state-metrics:
    enabled: true
    networkPolicy:
      enabled: true
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: mon
              operator: In
              values:
              - "true"
        - weight: 10
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "mon"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources: 
      limits:
        cpu: 1
        memory: 128Mi
        ephemeral-storage: 1Gi
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 10Mi    
  
  prometheus-node-exporter:
    enabled: true
    daemonsetAnnotations: 
      kube-score/ignore: pod-probes
    resources: 
      limits:
        cpu: 1
        memory: 1Gi
        ephemeral-storage: 1Gi
      requests:
        cpu: 10m
        memory: 16Mi
        ephemeral-storage: 10Mi    
    networkPolicy:
      enabled: true
    
  networkPolicy:
    enabled: true
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
      ephemeral-storage: 1Gi
    requests:
      cpu: 10m
      memory: 16Mi
      ephemeral-storage: 10Mi    
