{
 "title": "Incident dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Account", "label": "Account", "query": { "query": "label_values(cluster)" } },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "custom_interval",
    "label": "Interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "5xx_threshold", "label": "5xx threshold", "query": "0, 0.1, 1, 10" },
   { "name": "4xx_threshold", "label": "4xx threshold", "query": "0, 0.1, 1, 10" },
   { "name": "error_pages_threshold", "label": "Error pages threshold", "query": "0, 0.1, 1, 10" },
   {
    "name": "load_balancer",
    "label": "load_balancer",
    "query": {
     "query": "label_values(aws_applicationelb_target_response_time_average{cluster=~\"$Account\"},load_balancer)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "datasource",
   "options": {
    "content": "<center><h1>Account: $Account</h1></center>"
   }
  },
  {
   "title": "5XX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "datasource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=~\"5.*\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_workload) > $5xx_threshold",
     "legendFormat": "Istio - {{ destination_workload }}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "expr": "sum(irate(aws_applicationelb_httpcode_elb_5_xx_count_sum{load_balancer=~\"$load_balancer\",cluster=~\"^$Account$\"}[$__rate_interval])) by (load_balancer) > $5xx_threshold",
     "legendFormat": "ALB - {{load_balancer}}"
    },
    {
     "expr": "sum(irate(aws_applicationelb_httpcode_target_5_xx_count_sum{load_balancer=~\"$load_balancer\",cluster=~\"^$Account$\"}[$__rate_interval])) by (load_balancer) > $5xx_threshold",
     "legendFormat": "ALB {{load_balancer}} targets"
    }
   ]
  },
  {
   "title": "4XX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "repeat": "datasource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=~\"4.*\"}[$__rate_interval])) by (destination_workload) > $4xx_threshold",
     "legendFormat": "Istio - {{ destination_workload }}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    },
    {
     "expr": "sum(irate(haproxy_backend_http_responses_total{code=~\"4xx\",instance=~'.*'}[$__rate_interval])) by (proxy) > $4xx_threshold",
     "legendFormat": "HAProxy - {{ proxy }}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "ERROR PAGES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "repeat": "datasource",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(probe_http_status_code{instance=~\"https://.+\",cluster=~\"^$Account$\"}[$__rate_interval])) by (target) >= $error_pages_threshold",
     "legendFormat": "{{ target }}",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "$Account overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "repeat": "datasource",
   "collapsed": true,
   "panels": [
    {
     "title": "Global Request Volume",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{reporter=\"destination\",cluster=~\"^$Account$\"}[1m])), 0.001)",
       "legendFormat": "Requests per second"
      }
     ]
    },
    {
     "title": "Global Success Rate (non-5xx responses)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(istio_requests_total{reporter=\"destination\", response_code!~\"5.*\",cluster=~\"^$Account$\"}[$__range])) / sum(rate(istio_requests_total{reporter=\"destination\",cluster=~\"^$Account$\"}[$__range])))*100",
       "legendFormat": "Success Rate %"
      }
     ]
    },
    {
     "title": "P95",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 23, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(histogram_quantile(0.95, sum(irate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",cluster=~\"^$Account$\"}[1m])) by (le, destination_workload)) / 1000) or histogram_quantile(0.95, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",cluster=~\"^$Account$\"}[1m])) by (le, destination_workload))",
       "legendFormat": "{{ destination_workload }}"
      }
     ]
    },
    {
     "title": "HTTP/GRPC Workloads",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 23, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=\"200\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload, destination_workload_namespace)",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "sum(rate(istio_requests_total{reporter=\"destination\", response_code=\"200\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload, destination_workload_namespace) * 60",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "(histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",cluster=~\"^$Account$\"}[$__range])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\",cluster=~\"^$Account$\"}[$__range])) by (le, destination_workload, destination_workload_namespace))",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "(histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",cluster=~\"^$Account$\"}[$__range])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\",cluster=~\"^$Account$\"}[$__range])) by (le, destination_workload, destination_workload_namespace))",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "(sum(irate(istio_requests_total{reporter=\"destination\", response_code!~\"5.*\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload, destination_workload_namespace) / sum(irate(istio_requests_total{reporter=\"destination\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload, destination_workload_namespace))",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=~\"4.*\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload, destination_workload_namespace) > 0.01",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=~\"5.*\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload, destination_workload_namespace) > 0.01",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"4.*\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload, destination_workload_namespace) > 0.01",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"source\", response_code=~\"5.*\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload, destination_workload_namespace) > 0.01",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"source\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload, destination_workload_namespace) > 0.01",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      }
     ]
    },
    {
     "title": "5xxs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "Delfi Linux servers" },
       "host": { "filter": "http-checks" },
       "item": { "filter": "50X requests EE" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "expr": "sum(irate(istio_requests_total{reporter=\"destination\", response_code=~\"5.*\",cluster=~\"^$Account$\"}[$__range])) by (destination_workload)",
       "legendFormat": "Istio {{ destination_workload }}"
      }
     ]
    }
   ]
  }
 ]
}