{
 "title": "Kubernetes nodes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Account", "label": "Account", "query": { "query": "label_values(cluster)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$node\",cluster=~\"$Account\"},instance)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\",cluster=~\"$Account\"}, nodename)"
    }
   },
   {
    "name": "pods_interval",
    "label": "Pods interval",
    "query": "1m,3m, 5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "custom_interval",
    "label": "Interval",
    "query": "15s, 30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cpu_threshold",
    "label": "CPU threshold",
    "query": "None : 0, 1m : 0.001, 10m : 0.01, 100m : 0.1, 1 core : 1, 10 cores : 10"
   },
   {
    "name": "memory_threshold",
    "label": "Memory threshold",
    "query": "None : 0, 1M : 1, 10M : 10, 100M : 100, 1G : 1024, 10G : 10240"
   },
   {
    "name": "system_namespaces",
    "query": "kube-system|istio-system|istio-ingress"
   }
  ]
 },
 "panels": [
  { "title": "Node current status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=~\"$Account\"}[$__rate_interval])) by (instance, cluster) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(kube_node_spec_taint{cluster=~\"$Account\"}, \"nodename\", \"$1\", \"node\", \"(.+)\")) by (nodename, key)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 17, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{cluster=~\"$Account\"} / (node_memory_MemTotal_bytes{cluster=~\"$Account\"}) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"})) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(kube_node_spec_taint{cluster=~\"$Account\"}, \"nodename\", \"$1\", \"node\", \"(.+)\")) by (nodename, key)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes ready",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\", node=~\"$node\",cluster=~\"$Account\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "kube_node_status_condition{node=~\"$node\", cluster=~\"$Account\", condition!=\"Ready\", status=\"true\"} > 0",
     "legendFormat": "{{ node }} - {{ condition }}"
    },
    {
     "expr": "kube_node_spec_unschedulable{node=~\"$node\", cluster=~\"$Account\"} > 0",
     "legendFormat": "{{ node }} - unschedulable"
    }
   ]
  },
  {
   "title": "Avg CPU by taints",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=~\"$Account\"}[$__rate_interval])) by (instance, cluster) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(kube_node_spec_taint{cluster=~\"$Account\"}, \"nodename\", \"$1\", \"node\", \"(.+)\")) by (nodename, key)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg memory by taints",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{cluster=~\"$Account\"} / (node_memory_MemTotal_bytes{cluster=~\"$Account\"}) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"})) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(label_replace(kube_node_spec_taint{cluster=~\"$Account\"}, \"nodename\", \"$1\", \"node\", \"(.+)\")) by (nodename, key)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System namespaces (kube-system / istio-system / istio-ingress)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "High CPU (>70%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=~\"$Account\", namespace=~\"$system_namespaces\"}) by (pod) / sum(kube_pod_container_resource_limits{cluster=~\"$Account\", namespace=~\"$system_namespaces\"}) by (pod)) > 0.7",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "High memory (>70%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(container_memory_rss{cluster=~\"$Account\", namespace=~\"$system_namespaces\",container!=\"POD\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\",cluster=~\"$Account\", namespace=~\"$system_namespaces\"}) by (pod)) > 0.7",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  { "title": "CPU statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"$instance\", cluster=~\"$Account\"}[$__interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"$instance\", cluster=~\"$Account\"})\n) by (instance) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}\n",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "CPU Usage (system)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(node_cpu_seconds_total{mode!~\"(user|idle)\",instance=~\"$instance\", cluster=~\"$Account\"}[$__rate_interval])) by (instance) / count(node_cpu_seconds_total{mode=\"idle\", cluster=~\"$Account\"}) by (instance)) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
     "legendFormat": "{{ nodename }}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(increase(container_cpu_cfs_throttled_periods_total{node=~\"$node\", container!~\"POD\",image!=\"\", cluster=~\"$Account\"}[5m])) by (node) / sum(increase(container_cpu_cfs_periods_total{node=~\"$node\", container!~\"POD\", image!=\"\", cluster=~\"$Account\"}[5m])) by (node))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_memory_MemAvailable_bytes{instance=~\"$instance\", job=\"node-exporter\", cluster=~\"$Account\"}) by (instance) * on (instance) group_right (nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\", job=\"node-exporter\", cluster=~\"$Account\"}) by (instance) * on (instance) group_right (nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}"
      },
      {
       "expr": "sum(node_uname_info{instance=~\"$instance\", nodename=~\"$node\", cluster=~\"$Account\"}) by (instance, nodename)"
      },
      {
       "expr": "sum(label_replace(vmware_vm_memory_max{vm_name=~\"$node\", cluster=~\"$Account\"}, \"nodename\", \"$1\", \"vm_name\", \"(.+)\")) by (nodename, host_name)"
      },
      {
       "expr": "sum(vmware_host_memory_usage{cluster=~\"$Account\"}) by (host_name)"
      },
      {
       "expr": "sum(vmware_host_memory_max{cluster=~\"$Account\"}) by (host_name)"
      }
     ]
    },
    {
     "title": "Node memory usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(\n  sum(node_memory_MemTotal_bytes{job=\"node-exporter\", cluster=~\"$Account\"}) by (instance)\n-\n  sum(node_memory_MemFree_bytes{job=\"node-exporter\", cluster=~\"$Account\"}) by (instance)\n-\n  sum(node_memory_Buffers_bytes{job=\"node-exporter\", cluster=~\"$Account\"}) by (instance)\n-\n  sum(node_memory_Cached_bytes{job=\"node-exporter\", cluster=~\"$Account\"}) by (instance)\n) * on (instance) group_right (nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}\n",
       "legendFormat": "{{ nodename }} used"
      },
      {
       "expr": "sum(node_memory_Buffers_bytes{job=\"node-exporter\", cluster=~\"$Account\"}) by (instance) * on (instance) group_right (nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} buffer"
      },
      {
       "expr": "sum(node_memory_Cached_bytes{job=\"node-exporter\", cluster=~\"$Account\"}) by (instance) * on (instance) group_right (nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} cache"
      },
      {
       "expr": "sum(node_memory_MemFree_bytes{job=\"node-exporter\", cluster=~\"$Account\"}) * on (instance) group_right (nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} free"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O (read)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=~\"$instance\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=~\"$Account\"}[$__interval])) by (instance)",
       "legendFormat": "[{{ instance }}] {{device}}"
      }
     ]
    },
    {
     "title": "Disk I/O (write)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=~\"$instance\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=~\"$Account\"}[$__interval])) by (instance)",
       "legendFormat": "[{{ instance }}] {{device}} written"
      }
     ]
    },
    {
     "title": "Disk I/O (io time)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{job=\"node-exporter\", instance=~\"$instance\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", cluster=~\"$Account\"}[$__interval])) by (instance)",
       "legendFormat": "[{{ instance }}] {{device}} io time"
      }
     ]
    },
    {
     "title": "Disk Space Available",
     "type": "graph",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", cluster=~\"$Account\"}) by (instance, device)\n/\nsum(node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", cluster=~\"$Account\"}) by (instance, device))",
       "legendFormat": "{{ instance }} {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network outage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unusually small network received",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "((sum(irate(node_network_receive_bytes_total{job=\"node-exporter\", instance=~\"$instance\", device!=\"lo\", cluster=~\"$Account\"}[$__rate_interval])) by (instance) * 2) < sum(rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=~\"$instance\", device!=\"lo\", cluster=~\"$Account\"}[1d])) by (instance) ) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }}"
      }
     ]
    },
    {
     "title": "TCP Aborts / Timeouts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnClose{instance=~\"$instance\", cluster=~\"$Account\"}[$__rate_interval]) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} - TCPAbortOnClose"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnMemory{instance=~\"$instance\", cluster=~\"$Account\"}[$__rate_interval]) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} - TCPAbortOnMemory"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnTimeout{instance=~\"$instance\", cluster=~\"$Account\"}[$__rate_interval]) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} - TCPAbortOnTimeout"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortFailed{instance=~\"$instance\", cluster=~\"$Account\"}[$__rate_interval]) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} - TCPAbortFailed"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPTimeouts{instance=~\"$instance\", cluster=~\"$Account\"}[$__rate_interval]) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} - TCPTimeouts"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnData{instance=~\"$instance\", cluster=~\"$Account\"}[$__rate_interval]) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} - TCPAbortOnData"
      },
      {
       "expr": "irate(node_netstat_TcpExt_TCPAbortOnLinger{instance=~\"$instance\", cluster=~\"$Account\"}[$__rate_interval]) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} - TCPAbortOnLinger"
      }
     ]
    }
   ]
  },
  {
   "title": "Network statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Received",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{job=\"node-exporter\", instance=~\"$instance\", device!=\"lo\", cluster=~\"$Account\"}[$__interval])) by (instance) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }}"
      }
     ]
    },
    {
     "title": "Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(node_network_transmit_bytes_total{job=\"node-exporter\", device!=\"lo\", instance=~\"$instance\", cluster=~\"$Account\"}[$__rate_interval])) by (instance, device) * on (instance) group_left(nodename) node_uname_info{nodename=~\"$node\", cluster=~\"$Account\"}",
       "legendFormat": "{{ nodename }} - {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU per namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "state-timeline",
     "gridPos": { "h": 31, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$node\", cluster=~\"$Account\"}) by (namespace) > $cpu_threshold",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory per namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "state-timeline",
     "gridPos": { "h": 31, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{node=~\"$node\", cluster=~\"$Account\"}) by (namespace) > ($memory_threshold * 1024 * 1024)",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods per namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployments",
     "type": "state-timeline",
     "gridPos": { "h": 31, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=~\"$node\",created_by_kind=~\"DaemonSet|ReplicaSet\", cluster=~\"$Account\"}) by (namespace)",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources per namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU utilization",
     "type": "state-timeline",
     "gridPos": { "h": 31, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=~\"$node\", cluster=~\"$Account\"}) by (namespace) / sum(kube_pod_container_resource_limits{node=~\"$node\",resource=\"cpu\", cluster=~\"$Account\"}) by (namespace)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Memory utilization",
     "type": "state-timeline",
     "gridPos": { "h": 31, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{node=~\"$node\",container!=\"POD\",container!=\"\", cluster=~\"$Account\"}) by (namespace) / sum(kube_pod_container_resource_limits{node=~\"$node\",resource=\"memory\", cluster=~\"$Account\"}) by (namespace)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Jobs",
     "type": "state-timeline",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "count(kube_pod_info{node=~\"$node\",created_by_kind=~\"Job\", cluster=~\"$Account\"}) by (namespace)",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  }
 ]
}