argocd:
  global:
    domain: ${hostname}
  configs:
    cm:
      accounts.infralib: apiKey
    rbac:
      policy.csv: |
        p, infralib, applications, get, */*, allow
        p, infralib, applications, sync, */*, allow
        p, infralib, projects, get, *, allow

  crds:
    install: ${install_crd}
  server:
    service:
      annotations:
        cloud.google.com/backend-config: '{"ports": {"http":"${namespace}-server"}}'
    ingress:
      annotations: 
        alb.ingress.kubernetes.io/group.name: ${ingress_group_name}
        alb.ingress.kubernetes.io/scheme: ${ingress_scheme}

