{{- if and (eq .Values.global.cloudProvider "aws") .Values.global.createClusterSecretStore }}

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{.Values.global.aws.region}}
      auth:
        jwt:
          serviceAccountRef:
            name: secret-manager-operator

{{- end }}