cloudProvider: google
providerConfigRefName: crossplane-google

google:
  projectID: ""

external-dns:
  sources:
    - service
    - ingress
    - istio-gateway
    - istio-virtualservice
    - gateway-httproute
  extraArgs:
    - --metrics-address=:7979
    - --zone-id-filter=""
    - --zone-id-filter=""
    - --zone-id-filter=""
  provider:
    name: google
  serviceAccount:
    create: true
