cloudProvider: google
kubernetesServiceAccount: ""
kubernetesNamespace: ""
projectID: ""
managedZone: ""
installProvider: true

external-dns:
  provider:
    name: google
  serviceAccount:
    create: true
