awsAccount: ""
clusterOIDC: ""
providerConfigRefName: aws-crossplane-system

external-dns:
  serviceAccount:
    create: false
    name: "external-dns"

  env: 
  - name: AWS_DEFAULT_REGION
    value: ""

  registry: txt
  policy: upsert-only
  sources:
    - service
    - ingress

  extraArgs:
  - --metrics-address=:7979

  serviceMonitor:
    enabled: false
    scrapeTimeout: 20s
    additionalLabels: 
      kubernetes.io/metadata.name: monitoring
      release: prometheus

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
      ephemeral-storage: 10Gi
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 1Gi
      
  deploymentAnnotations:
    kube-score/ignore: pod-networkpolicy,pod-probes
