global:
  cloudProvider: aws
  providerConfigRefName: crossplane-aws

  aws:
    account: ""
    clusterOIDC: ""
    assumeRole: ""

external-dns:
  sources:
    - service
    - ingress
    - istio-gateway
    - istio-virtualservice
  env:
    - name: AWS_DEFAULT_REGION
      value: ""
  serviceAccount:
    create: false
    name: "external-dns"
