awsAccount: ""
clusterOIDC: ""
providerConfigRefName: aws-crossplane-system

external-dns:
  serviceAccount:
    create: false
    name: "external-dns"

  env: 
  - name: AWS_DEFAULT_REGION
    value: ""

  registry: txt
  policy: upsert-only
  sources:
    - service
    - ingress
    - istio-gateway
    - istio-virtualservice
  extraArgs:
  - --metrics-address=:7979

  serviceMonitor:
    enabled: false
    scrapeTimeout: 20s
    additionalLabels: 
      kubernetes.io/metadata.name: monitoring
      release: prometheus
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        preference:
          matchExpressions:
          - key: tools
            operator: In
            values:
            - "true"
  tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
      ephemeral-storage: 10Gi
    requests:
      cpu: 50m
      memory: 64Mi
      ephemeral-storage: 1Gi
      
  deploymentAnnotations:
    kube-score/ignore: pod-networkpolicy,pod-probes
