cloudProvider: google
providerConfigRefName: google-crossplane-system

google:
  projectID: ""

external-dns:
  sources:
    - service
    - ingress
    - istio-gateway
    - istio-virtualservice
    - gateway-httproute
  provider:
    name: google
  serviceAccount:
    create: true
