cloudProvider: aws

awsAccount: ""
clusterOIDC: ""
providerConfigRefName: crossplane-aws

external-dns:
  sources:
    - service
    - ingress
    - istio-gateway
    - istio-virtualservice
  env:
    - name: AWS_DEFAULT_REGION
      value: ""
