global:
  cloudProvider: "azure"

wireguard:
  tolerations:
    - key: "tools"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "mon"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
  keygenJob:
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
