{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketIAMMember
metadata:
  name: {{ .Release.Name }}-storage-object-admin
spec:
  forProvider:
    bucketRef:
        name: {{ .Values.global.bucketName }}
    member: serviceAccount:{{ .Values.global.google.projectID }}.svc.id.goog[{{ .Release.Namespace }}/{{ .Values.loki.serviceAccount.name }}]
    role: roles/storage.objectAdmin
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
    
{{- end }}
