{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: Secret
metadata:
  name: {{ .Release.Name }}-loki-hostname
  annotations:
    crossplane.io/external-name: "entigo-infralib-{{ .Values.global.prefix }}-loki_hostname"
spec:
  forProvider:
    annotations:
      product: entigo-infralib
      prefix: {{ .Release.Name }}
      parameter: secret
    labels:
      crossplane: "true"
    replication:
      - auto: [{}]
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: {{ .Release.Name }}-loki-hostname
spec:
  forProvider:
    secretDataSecretRef:
      key: hostname
      name: loki-hostname # Kubernetes secret name
      namespace: {{ .Release.Namespace }}
    secretRef:
      name: {{ .Release.Name }}-loki-hostname # Crossplane secret name
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: loki-hostname
data:
  hostname: {{ .Release.Namespace | printf "loki-gateway.%s.svc.cluster.local" | b64enc | quote }}

{{- end }}
