kyverno:
  crds:
    migration:
      tolerations:
        - key: "tools"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
  admissionController:
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
  backgroundController:
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
  cleanupController:
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
  reportsController:
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
  webhooksCleanup:
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
