{{- if .Values.installCompositeResources }}
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositewebaccesses.networking.entigo.com
spec:
  compositeTypeRef:
    apiVersion: networking.entigo.com/v1alpha1
    kind: CompositeWebAccess
  mode: Pipeline
  pipeline:
    - step: web-access
      functionRef:
        name: developer-portal-function
      input:
        apiVersion: template.fn.crossplane.io/v1beta1
        kind: Input
{{- end }}
