{
 "title": "Logs",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "label": "Account", "query": { "query": "label_values(cluster)" } },
   { "name": "loki_source", "label": "Loki instance", "query": "loki" },
   { "name": "search", "label": "Search" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "app",
    "label": "App",
    "query": {}
   },
   { "name": "custom_interval", "label": "Interval", "query": "20s,1m,10m,30m,1h,6h" }
  ]
 },
 "panels": [
  {
   "title": "Application timeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Timeline",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count_over_time({cluster=~\"^$Account$\",namespace=\"$namespace\",container!=\"istio-proxy\",container=~\"$container\",pod=~\"$pod\"} |~ \"(?i)$search\" |~ \"error\" [$custom_interval]))"
      },
      {
       "expr": "sum(count_over_time({cluster=~\"^$Account$\",namespace=~\"$namespace\",container!~\"istio-proxy\",container=~\"$container\",pod=~\"$pod\"} |~ \"(?i)$search\" [$custom_interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Application logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application",
     "type": "logs",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{cluster=~\"^$Account$\",namespace=\"$namespace\",container!=\"istio-proxy\",pod=~\"$pod\",container=~\"$container\",app=~\"$app\"} |~ \"(?i)$search\" | json",
       "maxLines": 2000
      }
     ]
    }
   ]
  },
  {
   "title": "Istio proxy timeline",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timeline",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate({cluster=~\"^$Account$\",container=\"istio-proxy\",namespace=\"$namespace\",pod=~\"$pod\",app=~\"$app\"} |~ `(?i)$search` | json | line_format \"{{ .log }}\" [$custom_interval]))",
       "maxLines": 1000
      }
     ]
    }
   ]
  },
  { "title": "Istio proxy logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Istio proxy",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{cluster=~\"^$Account$\",container=\"istio-proxy\",namespace=\"$namespace\",pod=~\"$pod\",app=~\"$app\"} | json |~ `(?i)$search`",
     "maxLines": 1000,
     "resolution": 1
    }
   ]
  },
  {
   "title": "Kubernetes events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Timeline",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum(rate({cluster=~\"^$Account$\",namespace=\"$namespace\", cluster!=\"\"}[$custom_interval]))",
       "legendFormat": "{{ .msg }}",
       "maxLines": 2000
      }
     ]
    },
    {
     "title": "Events",
     "type": "logs",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", cluster!=\"\"}",
       "legendFormat": "{{ .msg }}",
       "maxLines": 2000
      }
     ]
    }
   ]
  },
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Search examples",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "options": {
    "content": "<h4>Istio proxy</h4>\n\n- **Response code:** `response_code\":5`"
   }
  }
 ]
}