{
 "title": "MySQL Database Analytics",
 "tags": [ "developer" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Account", "label": "Account", "query": { "query": "label_values(cluster)" } },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "custom_interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "schema",
    "label": "Database",
    "query": {
     "query": "label_values(mysql_info_schema_table_rows{cluster=~\"^$Account$\"}, schema)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(mysql_info_schema_table_rows{cluster=~\"^$Account$\"}, table)"
    }
   },
   { "name": "Filters" },
   {
    "name": "range_seconds",
    "query": {
     "query": "query_result(label_replace(label_replace(label_replace(label_replace(vector(1),\"period_s\",\"${__range}\",\"\",\"\"),\"period_s\",\"(60*$1)\",\"period_s\",\"([0-9]+)m\"),\"period_s\",\"(3600*$1)\",\"period_s\",\"([0-9]+)h\"),\"period_s\",\"(86400*$1)\",\"period_s\",\"([0-9]+)d\"))\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tables",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(mysql_info_schema_table_size{component=\"data_length\", schema=~\"$schema\",table!~\"slow_log.*\",cluster=~\"^$Account$\"}) by (table)"
    },
    {
     "expr": "sum(mysql_info_schema_table_rows{schema=~\"$schema\",table!~\"slow_log.*\",cluster=~\"^$Account$\"}) by (table)"
    },
    {
     "expr": "sum(mysql_info_schema_table_size{component=\"index_length\", schema=~\"$schema\",table!~\"slow_log.*\",cluster=~\"^$Account$\"}) by (table)"
    },
    {
     "expr": "sum(mysql_info_schema_table_size{component=\"data_free\", schema=~\"$schema\",table!~\"slow_log.*\",cluster=~\"^$Account$\"}) by (table)"
    }
   ]
  },
  {
   "title": "Auto increment fields",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mysql_info_schema_auto_increment_column{schema=~\"$schema\",table!~\"slow_log.*\",cluster=~\"^$Account$\"}) by (table, column)"
    },
    {
     "expr": "sum(mysql_info_schema_auto_increment_column_max{schema=~\"$schema\",table!~\"slow_log.*\",cluster=~\"^$Account$\"}) by (table, column)"
    },
    {
     "expr": "round(sum(mysql_info_schema_auto_increment_column{schema=~\"$schema\",table!~\"slow_log.*\",cluster=~\"^$Account$\"}) by (table, column) / sum(mysql_info_schema_auto_increment_column_max{schema=~\"$schema\",table!~\"slow_log.*\",cluster=~\"^$Account$\"}) by (table, column), 0.0001)"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Query Analytics",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(mysql_perf_schema_events_statements_tmp_tables_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) > 0"
    },
    {
     "expr": "sum(increase(mysql_perf_schema_events_statements_sort_merge_passes_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) > 0",
     "legendFormat": "Sort merge passes"
    },
    {
     "expr": "sum(increase(mysql_perf_schema_events_statements_sort_rows_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) > 0",
     "legendFormat": "Sort rows"
    },
    {
     "expr": "sum(increase(mysql_perf_schema_events_statements_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) > 0",
     "legendFormat": "Count"
    },
    {
     "expr": "sum(irate(mysql_perf_schema_events_statements_tmp_disk_tables_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) > 0",
     "legendFormat": "Temp disk tables"
    },
    {
     "expr": "sum(increase(mysql_perf_schema_events_statements_rows_examined_total {schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) > 0",
     "legendFormat": "Rows examined"
    },
    {
     "expr": "sum(increase(mysql_perf_schema_events_statements_rows_affected_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) > 0",
     "legendFormat": "Rows affected"
    },
    {
     "expr": "sum(increase(mysql_perf_schema_events_statements_rows_sent_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) > 0",
     "legendFormat": "Rows sent"
    },
    {
     "expr": "(sum(increase(mysql_perf_schema_events_statements_seconds_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) / sum(increase(mysql_perf_schema_events_statements_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text) > 0) > 0",
     "legendFormat": "Average time"
    },
    {
     "expr": "(sum(increase(mysql_perf_schema_events_statements_seconds_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__range])) by (schema, digest_text)) > 0",
     "legendFormat": "Total time"
    }
   ]
  },
  {
   "title": "Index not used",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(irate(mysql_perf_schema_events_statements_no_index_used_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[1h])) by (schema, digest_text) > 0",
     "legendFormat": "[no index] - {{ digest_text }}"
    },
    {
     "expr": "sum(irate(mysql_perf_schema_events_statements_sum_no_good_index_used{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[1h])) by (schema, digest_text) > 0",
     "legendFormat": "[no good index] - {{ digest_text }}"
    }
   ]
  },
  {
   "title": "Query executions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(irate(mysql_perf_schema_events_statements_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__rate_interval])) by (schema, digest_text)",
     "legendFormat": "{{ digest_text }}"
    }
   ]
  },
  { "title": "Problems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Query errors",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(irate(mysql_perf_schema_events_statements_errors_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__rate_interval])) by (schema, digest_text) > 0",
     "legendFormat": "{{ schema }} - {{ digest_text }}"
    }
   ]
  },
  {
   "title": "Query warnings",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(irate(mysql_perf_schema_events_statements_warnings_total{schema=~\"$schema\",table=~\"$table\",cluster=~\"^$Account$\"}[$__rate_interval])) by (schema, digest_text) > 0",
     "legendFormat": "[warn] {{ schema }} - {{ digest_text }}"
    }
   ]
  }
 ]
}