global:
  registry: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}'
  aws:
    region: "{{ .toutput.eks.region }}"
    vpc:
      name: "{{ .toutput.vpc.name }}"
      id: "{{ .toutput.vpc.vpc_id }}"
      cidr: "{{ .toutput.vpc.vpc_cidr_block }}"
      database_subnets_id: |
        {{ .toutput.vpc.database_subnets }}
      database_subnet_cidr: |
        {{ .toutput.vpc.database_subnets_cidr_blocks }}
      database_subnet_group_name: |
        {{ .toutput.vpc.database_subnet_group_name }}
    kms:
      data_name: "{{ .config.prefix }}-data"
      data_key_arn: "{{ .toutput.kms.data_key_arn }}"
