installProviderConfig: true

global:
  extraProviders: []
  defaultProviders: ["iam", "s3", "sqs", "ecr", "rds", "kms", "secretsmanager", "ec2", "eks"]
  cloudProvider: ""
  aws:
    role: ""
  deploymentRuntimeConfig:
    args:
      - --enable-management-policies
