{{- if eq .Values.cloudProvider "aws" }}

apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }} 
spec:
  forProvider:
    name: {{ .Release.Name }}
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:ListObjects*",
              "s3:ListBucket",
              "s3:PutObject",
              "s3:GetObject",
              "s3:DeleteObject"
            ],
            "Resource": [
              "arn:aws:s3:::{{ .Values.harbor.persistence.imageChartStorage.s3.bucket }}/*"
            ]
          },
          {
            "Effect": "Allow",
            "Action": [
              "s3:ListBucket"
            ],
            "Resource": [
              "arn:aws:s3:::{{ .Values.harbor.persistence.imageChartStorage.s3.bucket }}"
            ]
          }
        ]
      }

  providerConfigRef:
    name: {{ .Values.providerConfigRefName }}

{{- end }}