{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ .Release.Name }}-workload-identity-user
spec:
  forProvider:
    member: serviceAccount:{{ .Values.global.google.projectID }}.svc.id.goog[{{ .Release.Namespace }}/mimir]
    project: {{ .Values.global.google.projectID }}
    role: roles/iam.workloadIdentityUser
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
    
{{- end }}
