{{- if eq .Values.cloudProvider "google" }}

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ .Release.Name }}-workload-identity-user
spec:
  forProvider:
    member: serviceAccount:{{ .Values.google.projectID }}.svc.id.goog[{{ .Values.global.namespaceName }}/{{ .Values.global.serviceAccountName }}]
    project: {{ .Values.google.projectID }}
    role: roles/iam.workloadIdentityUser
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ .Release.Name }}-storage-admin
spec:
  forProvider:
    member: serviceAccount:{{ .Values.google.projectID }}.svc.id.goog[{{ .Values.global.namespaceName }}/{{ .Values.global.serviceAccountName }}]
    project: {{ .Values.google.projectID }}
    role: roles/storage.admin
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
    
{{- end }}
