hostname: &useHostname "keycloak-biz-martivo-rd-150.runner-main-biz-int.infralib.entigo.io"

keycloak:
  proxy: edge
  production: true
  args:
  - "start"
  - "--hostname"
  - *useHostname
  - "--proxy"
  - "edge"
  image:
    registry: quay.io
    repository: phasetwo/phasetwo-keycloak
    tag: 23.0.4
    
  ingress:
    enabled: true
    hostname: *useHostname
    pathType: Prefix
    ingressClassName: "alb"
    annotations: 
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/group.name: external
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/success-codes: 200-499
      alb.ingress.kubernetes.io/target-type: ip

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        preference:
          matchExpressions:
          - key: tools
            operator: In
            values:
            - "true"
  tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      
  networkPolicy:
    enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
      ephemeral-storage: 1Gi
    requests:
      cpu: "100m"
      memory: "256Mi"
      ephemeral-storage: 10Mi
  postgresql:
    primary:
      annotations: 
        kube-score/ignore: pod-networkpolicy
      resources:
        limits: 
          cpu: 2000m
          memory: 2Gi
          ephemeral-storage: 1Gi
        requests:
          memory: 256Mi
          cpu: 250m
          ephemeral-storage: 10Mi
