keycloakx:
  image:
    repository: quay.io/phasetwo/phasetwo-keycloak
    tag: "23.0.7"
    pullPolicy: IfNotPresent
  
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "start"
    - "--http-enabled=true"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--hostname-strict-https=false"
    - "--spi-email-template-provider=freemarker-plus-mustache"
    - "--spi-email-template-freemarker-plus-mustache-enabled=true"
    - "--spi-theme-cache-themes=false"
  
  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  
  networkPolicy:
    enabled: true
  
  http:
    relativePath: "/"
  
  ingress:
    enabled: true
    ingressClassName: "alb"
    tls: []
    annotations: 
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
      alb.ingress.kubernetes.io/group.name: external
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/success-codes: 200-499
      alb.ingress.kubernetes.io/target-type: ip
  
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
      ephemeral-storage: 1Gi
    requests:
      cpu: "50m"
      memory: "256Mi"
      ephemeral-storage: 10Mi
