global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
harbor:
  externalURL: "https://{{ .tsmodule.harbor }}.{{ .toutput.route53.int_domain }}"
  expose:
    ingress:
      hosts:
        core: "{{ .tsmodule.harbor }}.{{ .toutput.route53.int_domain }}"
  persistence:
    imageChartStorage:
      s3:
        region: "{{ .toutput.eks.region }}"
        regionendpoint: "s3.{{ .toutput.eks.region }}.amazonaws.com"
