global:
  cloudProvider: google
  providerConfigRefName: crossplane-google

  google:
    hostname: ""
    projectID: ""
    gateway:
      name: google-gateway-external
      namespace: google-gateway
    bucket:
      location: europe-north1

harbor:
  expose:
    type: clusterIP
    tls:
      enabled: false
  persistence:
    imageChartStorage:
      type: gcs
      gcs:
        useWorkloadIdentity: true
        bucket: ""
  registry:
    serviceAccountName: harbor
    automountServiceAccountToken: true
