cloudProvider: google
providerConfigRefName: crossplane-google

google:
  hostname: ""
  projectID: ""
  region: EU
  gateway:
    name: google-gateway-external
    namespace: google-gateway

harbor:
  expose:
    type: clusterIP
    tls:
      enabled: false
  persistence:
    imageChartStorage:
      type: gcs
      gcs:
        useWorkloadIdentity: true
        bucket: ""
