cloudProvider: google
providerConfigRefName: crossplane-google
namespaceName: harbor

google:
  hostname: ""
  projectID: ""
  gateway:
    name: google-gateway-external
    namespace: google-gateway

harbor:
  expose:
    type: clusterIP
    tls:
      enabled: false
  persistence:
    imageChartStorage:
      type: gcs
      gcs:
        useWorkloadIdentity: true
        bucket: ""
  registry:
    serviceAccountName: harbor
    automountServiceAccountToken: true
