cloudProvider: google
providerConfigRefName: crossplane-google
namespaceName: harbor

google:
  hostname: ""
  projectID: ""
  gateway:
    name: google-gateway-external
    namespace: google-gateway

harbor:
  expose:
    type: clusterIP
    tls:
      enabled: false
  persistence:
    imageChartStorage:
      type: gcs
      gcs:
        useWorkloadIdentity: true
        bucket: ""
  registry:
    serviceAccountName: harbor
    automountServiceAccountToken: true
  # portal:
  #   serviceAccountName: harbor
  #   automountServiceAccountToken: true
  # core:
  #   serviceAccountName: harbor
  #   automountServiceAccountToken: true
  # trivy:
  #   serviceAccountName: harbor
  #   automountServiceAccountToken: true
  # jobservice:
  #   serviceAccountName: harbor
  #   automountServiceAccountToken: true
  # exporter:
  #   serviceAccountName: harbor
  #   automountServiceAccountToken: true
  # redis:
  #   serviceAccountName: harbor
  #   automountServiceAccountToken: true
  # nginx:
  #   serviceAccountName: harbor
  #   automountServiceAccountToken: true
  # database:
  #   serviceAccountName: harbor
  #   automountServiceAccountToken: true
