argocd:
  global:
    domain: ${hostname}

  configs:
    params:
      server.insecure: true
    cm:
      accounts.infralib: apiKey
    rbac:
      policy.csv: |
        p, infralib, applications, get, */*, allow
      
  crds:
    install: ${install_crd}
  
  server:
    config:
      url: https://${hostname}
    service:
      annotations:
        cloud.google.com/neg: '{"ingress": true}'
        cloud.google.com/backend-config: '{"ports": {"http":"argocd-server"}}'

    ingress:
      enabled: true
      controller: gke
      gke:
        backendConfig:
          healthCheck:
            checkIntervalSec: 30
            timeoutSec: 5
            healthyThreshold: 1
            unhealthyThreshold: 2
            type: HTTP
            requestPath: /healthz
            port: 8080
        frontendConfig:
          redirectToHttps:
            enabled: true
        managedCertificate:
          enabled: true
