#The password is irrelevant, only the username matters.

{{ if not (eq .Values.admin_user "") }}
apiVersion: v1
data:
  admin-password: {{ .Values.admin_password | b64enc  }}
  admin-user: {{ .Values.admin_user | b64enc  }}
kind: Secret
metadata:
  name: grafana

{{ end }}
