apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: loki 
spec:
  forProvider:
    name: loki
    document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "s3:ListObjects*",
              "s3:ListBucket",
              "s3:PutObject",
              "s3:GetObject",
              "s3:DeleteObject"
            ],
            "Resource": [
              "arn:aws:s3:::loki/*"
            ]
          },
          {
            "Effect": "Allow",
            "Action": [
              "s3:ListBucket"
            ],
            "Resource": [
              "arn:aws:s3:::loki"
            ]
          }
        ]
      }

  providerConfigRef:
    name: aws-{{ .Release.Name }}