apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: loki
spec:
  forProvider:
    policyArn: arn:aws:iam::{{ .Values.awsAccount }}:policy/{{ .Release.Name }}
    roleNameRef:
      name: loki
  providerConfigRef:
    name: aws-{{ .Release.Name }}