apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: s3-crossplane-bucket
  annotations:
    crossplane.io/external-name: loki
spec:
  forProvider:
    acl: private
    locationConstraint: eu-north-1
    publicAccessBlockConfiguration:
      blockPublicPolicy: true
      blockPublicAcls: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    accelerateConfiguration:
      status: Enabled
    versioningConfiguration:
      status: Suspended
    serverSideEncryptionConfiguration:
      rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
  providerConfigRef:
    name: aws-{{ .Release.Name }}