apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Release.Name }}
  annotations:
    crossplane.io/external-name: {{ .Release.Name }}
spec:
  forProvider:
    acl: private
    locationConstraint: {{ .Values.region }}
    publicAccessBlockConfiguration:
      blockPublicPolicy: true
      blockPublicAcls: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
    accelerateConfiguration:
      status: Enabled
    versioningConfiguration:
      status: Suspended
    serverSideEncryptionConfiguration:
      rules:
      - applyServerSideEncryptionByDefault:
          sseAlgorithm: AES256
  providerConfigRef:
    name: {{ .Values.providerConfigRefName }}
