global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
    region: "{{ .toutput.eks.region" }}"
karpenter:
  settings:
    clusterName: "{{ .toutput.eks.cluster_name }}"
