cloudProvider: ""
providerConfigRefName: ""

aws:
  account: ""
  clusterOIDC: ""
  region: ""

# https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/values.yaml

karpenter:
  serviceAccount:
    create: false
    name: karpenter
  replicas: 1
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 1
        memory: 1Gi
        ephemeral-storage: 2Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: DoesNotExist
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

  settings:
    clusterName: ""
    isolatedVPC: true
