{{- if .Values.installProviderConfig }}
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    helm.sh/resource-policy: keep
spec:
  credentials:
    source: InjectedIdentity

---

apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: k8s-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    helm.sh/resource-policy: keep  
spec:
  credentials:
    source: InjectedIdentity

{{- end }}
