{{- if .Values.installProviderConfig }}
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-{{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    helm.sh/resource-policy: keep
spec:
  credentials:
    source: InjectedIdentity
{{- end }}
