crossplane:
  image:
    repository: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}/crossplane/crossplane'

global:
  aws:
    region: "{{ .toutput.eks.region }}"
    ecrRole: "{{ .toutput.crossplane.iam_role_core }}"
#Not needed for now.
#  serviceAccount:
#    customAnnotations: 
#      eks.amazonaws.com/role-arn: "{{ .toutput.crossplane.iam_role_core }}"
