crossplane:
  image:
    repository: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}/crossplane/crossplane'

  serviceAccount:
    customAnnotations: 
      eks.amazonaws.com/role-arn: "{{ .toutput.crossplane.iam_role_core }}"
