apiVersion: v2
name: crossplane
description: Crossplane operator chart
type: application
version: 0.1.1
appVersion: "1.1"

dependencies:
  - name: crossplane
    version: 2.0.0-rc.0.283.ge4e442e27
    repository: https://charts.crossplane.io/master
