apiVersion: v2
name: crossplane
description: Crossplane operator chart
type: application
version: 0.1.1
appVersion: "1.1"

dependencies:
  - name: universal-crossplane
    version: 1.20.1-up.1
    repository: https://charts.upbound.io/stable
