{{- if and (eq .Values.global.cloudProvider "google") .Values.global.createClusterSecretStore }}

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}
spec:
  provider:
    gcpsm:
      projectID: {{.Values.global.google.projectID}}
      auth:
        workloadIdentity:
          clusterLocation: {{.Values.global.google.region}}
          clusterName: {{.Values.global.google.cluster.name}}
          serviceAccountRef:
            name: secret-manager-operator
            namespace: {{ .Release.Namespace }}

{{- end }}