{{- if and (eq .Values.global.cloudProvider "google") .Values.global.createClusterSecretStore }}

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ .Release.Name }}
spec:
  forProvider:
    member: serviceAccount:{{ .Values.global.google.projectID }}.svc.id.goog[{{ .Release.Namespace }}/secret-manager-operator]
    project: {{ .Values.global.google.projectID }}
    role: roles/secretmanager.secretAccessor
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
