{{- if and (eq .Values.global.cloudProvider "google") .Values.global.createClusterSecretStore }}

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Release.Name }}
  name: secret-manager-operator

{{- end }}