spec:
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: aws-load-balancer-tls
    jsonPointers:
    - /data
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: aws-load-balancer-webhook
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: aws-load-balancer-webhook
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - Retry=true
    retry:
      limit: 30 # Maximum number of retries
