global:
  providerConfigRefName: crossplane-aws
  aws:
    account: ""
    clusterOIDC: ""

aws-load-balancer-controller:
  serviceAccount:
    name: aws-load-balancer-controller
    create: false

  image:
    repository: 602401143452.dkr.ecr.eu-north-1.amazonaws.com/amazon/aws-load-balancer-controller
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        preference:
          matchExpressions:
          - key: tools
            operator: In
            values:
            - "true"
  tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  resources: 
    limits:
      cpu: 1000m
      memory: 512Mi
      ephemeral-storage: 10Gi
    requests:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 1Gi
  ingressClassConfig:
    default: true
  
  deploymentAnnotations:
    kube-score/ignore: pod-networkpolicy,pod-probes
