global:
  google:
    hostname: "{{ .tsmodule.kiali }}.{{ .toutput.dns.int_domain }}"
kiali-server:
  server:
    web_fqdn: "{{ .tsmodule.kiali }}.{{ .toutput.dns.int_domain }}"
  fullnameOverride: "{{ .tsmodule.kiali }}"
