global:
  google:
    hostname: "{{ .module.name }}.{{ .toutput.dns.int_domain }}"
kiali-server:
  server:
    web_fqdn: "{{ .module.name }}.{{ .toutput.dns.int_domain }}"
  deployment:
    instance_name: "{{ .module.name }}"
