global:
  cloudProvider: "google"

  google:
    hostname: ""
    gateway:
      name: google-gateway-external
      namespace: google-gateway

kiali-server:
  deployment:
    ingress:
      enabled: false
