cloudProvider: ""

google:
  certificateMap: ""
  hostname: ""

kiali-server:
  fullnameOverride: "kiali"
  istio_namespace: "istio-system"
  server:
    web_fqdn: ""
  external_services:
    prometheus:
      url: "http://prometheus-server.prometheus:80/"
  deployment:
    image_pull_policy: "IfNotPresent"
    pod_annotations:
      kube-score/ignore: pod-probes,pod-networkpolicy
    ingress:
      enabled: true
      class_name: "alb"
      override_yaml:
        metadata:
          annotations:
            alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
            alb.ingress.kubernetes.io/group.name: internal
            alb.ingress.kubernetes.io/healthcheck-path: /
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
            alb.ingress.kubernetes.io/scheme: internal
            alb.ingress.kubernetes.io/success-codes: 200-499
            alb.ingress.kubernetes.io/target-type: ip
    affinity:
      node:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
          - weight: 10
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    resources:
      limits:
        cpu: 2000m
        memory: 1Gi
        ephemeral-storage: 1Gi
      requests:
        cpu: "10m"
        memory: "64Mi"
        ephemeral-storage: 10Mi
