{{- if .Values.global.createExternal }} 

kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-external
  namespace: {{ .Release.Name }}
  annotations:
    networking.gke.io/certmap: {{ .Values.global.google.externalCertificateMap }}
spec:
  gatewayClassName: {{ .Values.global.google.externalGatewayClassName }}
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute

{{- end }}
---
{{- if .Values.global.createInternal }} 

kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-internal
  namespace: {{ .Release.Name }}
spec:
  gatewayClassName: {{ .Values.global.google.internalGatewayClassName }}
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
        namespaces:
          from: All
      tls:
        mode: Terminate
        options:
          networking.gke.io/cert-manager-certs: {{ .Values.global.google.internalCertificateMap }}
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute

{{- end }}