
istiod:
  global:
    defaultResources:
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 1000m
        memory: 512Mi
        ephemeral-storage: 10Gi
  pilot:
    podAnnotations:
      kube-score/ignore: pod-networkpolicy
    resources:
      requests:
        cpu: 100m
        memory: 2048Mi
        ephemeral-storage: 1Gi
      limits:
        cpu: 1000m
        memory: 4096Mi
        ephemeral-storage: 10Gi
