{{- if eq .Values.global.cloudProvider "aws" }}

{{- if .Values.createNodepool }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4", "8"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Release.Name }}
  limits:
    cpu: 10
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
{{- end }}
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .Release.Name }}
spec:
  tags:
    Name: {{ .Release.Name }}
  instanceProfile: {{ .Release.Name }}-karpenter-node-instance-profile
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.subnetTag }}
        kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
  amiSelectorTerms:
    - id: ami-0bd14c07a3e0f69cb

              
{{- end }}
