{{- if eq .Values.global.cloudProvider "aws" }}

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ .Release.Name }}
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4", "8"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ .Release.Name }}
  limits:
    cpu: 10
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ .Release.Name }}
spec:
  tags:
    Name: {{ .Release.Name }}
  instanceProfile: {{ .Release.Name }}-karpenter-node-instance-profile
  amiFamily: AL2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.settings.clusterName }}
  amiSelectorTerms:
    - id: ami-0bd14c07a3e0f69cb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-test
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-test
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate-cluster-test
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            requests:
              cpu: 1
              
{{- end }}
