{{- if eq .Values.global.cloudProvider "aws" }}

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ .Release.Name }}-karpenter-controller-role-karpenter-controller-policy
spec:
  forProvider:
    policyArn: arn:aws:iam::{{ .Values.global.aws.account }}:policy/{{ .Release.Name }}-karpenter-controller-policy
    roleRef:
      name: {{ .Release.Name }}-karpenter-controller-role
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
