{{- if eq .Values.cloudProvider "aws" }}

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.account }}:role/karpenter-controller-role-{{ .Values.karpenter.settings.clusterName }}
  name: {{ .Values.karpenter.serviceAccount.name }}

{{- end }}
