{{- if .Values.installControllerConfig }} 

apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: google-{{ .Release.Name }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.controllerConfig.googleServiceAccount}}
spec:
  serviceAccountName: crossplane
  
{{- end }}
