{{- if .Values.installProvider }}

apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-storage:v0.41.0
  controllerConfigRef:
    name: my-controller-config

{{- end }}
