{{- if eq .Values.cloudProvider "google" }}

apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketIAMMember
metadata:
  name: {{ .Release.Name }}-storage-object-admin
spec:
  forProvider:
    bucketRef:
        name: {{ .Values.harbor.persistence.imageChartStorage.gcs.bucket }}
    member: serviceAccount:{{ .Values.google.projectID }}.svc.id.goog[{{ .Release.Namespace }}/{{ .Values.harbor.registry.serviceAccountName }}]
    role: roles/storage.objectAdmin
  providerConfigRef:
    name: {{ .Values.providerConfigRefName }}
    
{{- end }}
