{{- if eq .Values.cloudProvider "google" }}

apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Release.Name }}-portal
  namespace: {{ .Release.Name }}
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 3
    unhealthyThreshold: 3
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: {{ .Release.Name }}-portal
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Release.Name }}-core
  namespace: {{ .Release.Name }}
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 3
    unhealthyThreshold: 3
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /api/v2.0/ping
  targetRef:
    group: ""
    kind: Service
    name: {{ .Release.Name }}-core
{{- end }}
