{{- if .Values.createInternal }} 

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-redirect
  namespace: {{ .Release.Name }}
spec:
  parentRefs:
  - kind: Gateway
    name: {{ .Release.Name }}
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301

{{- end }}