{{- $datasourcesPath := "grafana-datasources/*.{json,yaml}" }}
{{- range $path, $_ := .Files.Glob $datasourcesPath }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-datasource-%s" $.Release.Name (replace "." "-" (replace "/" "-" (base $path))) }}
  labels:
    grafana_datasource: "1"
data:
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
---
{{- end }}