apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  selector:
    istio: gateway
  servers:
  - hosts:
    - "{{ .Values.domain }}"
    {{- if .Values.altdomain }}
    {{- range $url := .Values.altdomain }}
    - "{{ $url }}"
    {{- end }}
    {{- end }}
    port:
      name: http
      number: 80
      protocol: HTTP 
