apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: '{{ .Values.global.aws.scheme }}'
    alb.ingress.kubernetes.io/group.name: '{{ .Values.global.aws.groupName }}'
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    {{- with .Values.global.aws.additionalIngressAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Release.Name }}
spec:
  rules:
  - host: '{{ .Values.ingress.hostName }}'
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              name: http
        path: /*
        pathType: ImplementationSpecific
