apiVersion: v2
name: platform-apis
description: Platform APIs
version: v0.2.58
appVersion: "v0.2.58"
dependencies:
  - name: platform-apis
    version: v0.2.58
    repository: oci://ghcr.io/entigolabs
