apiVersion: v2
name: platform-apis
description: Platform APIs
version: v0.2.60-rc.197.283.2
appVersion: "v0.2.60-rc.197.283.2"
dependencies:
  - name: platform-apis
    version: v0.2.60-rc.197.283.2
    repository: oci://ghcr.io/entigolabs
