apiVersion: v2
name: platform-apis
description: Platform APIs
version: v0.2.34
appVersion: "v0.2.34"
dependencies:
  - name: platform-apis
    version: v0.2.34
    repository: oci://ghcr.io/entigolabs
