metrics-server:
  deploymentAnnotations:
    kube-score/ignore: pod-networkpolicy,pod-probes
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 256Mi
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: tools
                operator: In
                values:
                  - "true"
  tolerations:
    - key: "tools"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
