{{- if and (eq .Values.global.cloudProvider "azure") .Values.global.azure.agcHealthCheck }}
apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ .Release.Name }}-gateway
    namespace: {{ .Release.Namespace }}
  default:
    interval: 5s
    timeout: 5s
    healthyThreshold: 1
    unhealthyThreshold: 3
    http:
      path: /
      match:
        statusCodes:
          - start: 200
            end: 299
{{- end }}
