{{- if eq .Values.global.cloudProvider "azure" }}
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  activate:
  - 'containers.storage.azure.upbound.io'
  - 'encryptionscopes.storage.azure.upbound.io'
{{- end }}
