{{- if eq .Values.global.cloudProvider "aws" }}

apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: {{ .Release.Name }}
  annotations:
    crossplane.io/external-name: "{{ .Release.Name }}:arn:aws:iam::{{ .Values.global.aws.account }}:policy/{{ .Release.Name }}"
spec:
  forProvider:
    policyArn: arn:aws:iam::{{ .Values.global.aws.account }}:policy/{{ .Release.Name }}
    roleRef:
      name: {{ .Release.Name }}
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
