external-secrets:
  installCRDs: true
  deploymentAnnotations: 
    kube-score/ignore: pod-networkpolicy
  resources: 
    limits:
      cpu: 1000m
      memory: 512Mi
      ephemeral-storage: 10Gi
    requests:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 1Gi
      
  webhook:
    deploymentAnnotations: 
      kube-score/ignore: pod-networkpolicy
    resources: 
      limits:
        cpu: 1000m
        memory: 512Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 1Gi
  
  certController:
    deploymentAnnotations: 
      kube-score/ignore: pod-networkpolicy
    resources: 
      limits:
        cpu: 1000m
        memory: 512Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 1Gi

awsAccount: ""
awsRegion: ""
clusterOIDC: ""
providerConfigRefName: aws-crossplane-system


gitlab_url: ""
gitlab_project: ""
gitlab_secet: ""
