global:
  cloudProvider: aws
  providerConfigRefName: crossplane-aws

  aws:
    account: ""
    region: ""
    clusterOIDC: ""

external-secrets:
  serviceAccount:
    create: false
    name: secret-manager-operator
