{{- if and (eq .Values.global.cloudProvider "azure") .Values.global.createRoute }}
apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Values.gateway.name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRef:
    group: ""
    kind: Service
    name: {{ .Values.gateway.name }}
    namespace: {{ .Release.Namespace }}
  default:
    interval: 5s
    timeout: 5s
    healthyThreshold: 1
    unhealthyThreshold: 3
    port: 15021
    http:
      path: /healthz/ready
      match:
        statusCodes:
          - start: 200
            end: 299
{{- end }}
