{{- if and (eq .Values.global.cloudProvider "azure") .Values.global.createClusterSecretStore }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    helm.sh/resource-policy: keep
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ printf "https://%s.vault.azure.net/" (base .Values.global.azure.vaultId) }}
      tenantId: {{ .Values.global.azure.tenantId }}
      serviceAccountRef:
        name: secret-manager-operator
        namespace: {{ .Release.Namespace }}
{{- end }}
