{{- if eq .Values.cloudProvider "google" }}

kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Values.gateway.name }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{ .Values.google.gateway.name }}
      sectionName: https
      namespace: {{ .Values.google.gateway.namespace }}
  hostnames: [ "*.{{ .Values.google.hostname }}", {{ .Values.google.hostname }} ]
  rules:
    - backendRefs:
        - name: {{ .Values.gateway.name }}
          port: 80

{{- end }}
