trivy-operator:
  service:
    headless: true
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/path: "/metrics"
  trivyOperator:
    scanJobCompressLogs: false
    scanJobAffinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: mon
                  operator: In
                  values:
                    - "true"
          - weight: 50
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
    scanJobTolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  trivy:
    slow: true
    severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
    resources:
      requests:
        cpu: 100m
        memory: 100M
        ephemeralStorage: "2Gi"
      limits:
        cpu: 1000m
        memory: 2000M
        ephemeralStorage: "5Gi"
  operator:
    metricsFindingsEnabled: true
    metricsVulnIdEnabled: true
    exposedSecretScannerEnabled: false
    sbomGenerationEnabled: false
    configAuditScannerEnabled: false
    rbacAssessmentScannerEnabled: false
    infraAssessmentScannerEnabled: false
    clusterComplianceEnabled: false

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
              - key: mon
                operator: In
                values:
                  - "true"
        - weight: 10
          preference:
            matchExpressions:
              - key: tools
                operator: In
                values:
                  - "true"
  tolerations:
    - key: "mon"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "tools"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  nodeCollector:
    useNodeSelector: false
    tolerations:
      - key: "mon"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
