{{- if .Values.installProviderConfig }}

apiVersion: azure.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    helm.sh/resource-policy: keep
spec:
  credentials:
    source: OIDCTokenFile
  oidcTokenFilePath: /var/run/secrets/azure/tokens/azure-identity-token
  clientID: {{ .Values.global.azure.clientId | quote }}
  tenantID: {{ .Values.global.azure.tenantId | quote }}
  subscriptionID: {{ .Values.global.azure.subscriptionId | quote }}
  storageUseAzureAD: true

{{- end }}
