apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  activate:
  - 'policies.iam.aws.upbound.io'
  - 'rolepolicyattachments.iam.aws.upbound.io'
  - 'roles.iam.aws.upbound.io'
{{- if .Values.global.aws.vpc.id }}
  - 'vpcs.ec2.aws.upbound.io'
  - 'subnets.ec2.aws.upbound.io'
  - 'securitygroups.ec2.aws.upbound.io'
{{- end }}
{{- if .Values.global.aws.vpc.database_subnet_group_name }}
  - 'subnetgroups.rds.aws.upbound.io'
{{- end }}
{{- if .Values.global.aws.kms.data_key_arn }}
  - 'keys.kms.aws.upbound.io'
  - 'aliases.kms.aws.upbound.io'
{{- end }}
{{- if .Values.global.aws.eks.cluster_name }}
  - 'clusters.eks.aws.upbound.io'
  - 'nodegroups.eks.aws.upbound.io'
  - 'launchtemplates.ec2.aws.upbound.io'
{{- end }}
