apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-aws
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: {{ .Values.global.registry }}/entigolabs/provider-family-aws:v2.0.2
  runtimeConfigRef:
    name: {{ .Release.Name }}

{{- if .Values.global.defaultProviders }}
{{- range $index, $provider := .Values.global.defaultProviders }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-{{ $provider }}
  annotations:
    argocd.argoproj.io/sync-wave: '{{ add 5 (div $index 5) }}'
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  skipDependencyResolution: true
  package: {{ $.Values.global.registry }}/entigolabs/provider-aws-{{ $provider }}:v2.0.2
  runtimeConfigRef:
    name: {{ $.Release.Name }}
{{- end }}
{{- end }}

{{- if .Values.global.extraProviders }}
{{- range $index, $provider := .Values.global.extraProviders }}
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-aws-{{ $provider }}
  annotations:
    argocd.argoproj.io/sync-wave: '{{ add 7 (div $index 4) }}'
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  skipDependencyResolution: true
  package: {{ $.Values.global.registry }}/entigolabs/provider-aws-{{ $provider }}:v2.0.2
  runtimeConfigRef:
    name: {{ $.Release.Name }}
{{- end }}
{{- end }}


