apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    helm.sh/resource-policy: keep
    storageclass.kubernetes.io/is-default-class: "false"
  name: {{ .Values.global.prefix }}gp2-retain
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp2
  #tagSpecification_1: "Environment={{ .Values.environment }}"
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    helm.sh/resource-policy: keep
    storageclass.kubernetes.io/is-default-class: "false"
  name: {{ .Values.global.prefix }}gp2-no-retain
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp2
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    helm.sh/resource-policy: keep
    storageclass.kubernetes.io/is-default-class: "true"
  name: {{ .Values.global.prefix }}gp3
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    helm.sh/resource-policy: keep
    storageclass.kubernetes.io/is-default-class: "false"
  name: {{ .Values.global.prefix }}gp3-no-retain
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
