{
 "title": "Apollo Server",
 "tags": [ "developer" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "label": "Account", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(apollo_server_starting{cluster=~\"^$Account$\"}, namespace)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "custom_interval",
    "label": "Interval",
    "query": "3m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "percentile", "label": "Percentile", "query": "P50 : 50,P95 : 95,P99 : 99" }
  ]
 },
 "panels": [
  {
   "title": "Query duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(irate(apollo_query_duration_bucket{operation=\"query\", namespace=\"$namespace\",cluster=~\"^$Account$\"}[$__rate_interval])) by (le, operationName)) > 0",
     "legendFormat": "{{ operationName }}"
    }
   ]
  },
  {
   "title": "Mutation duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(irate(apollo_query_duration_bucket{operation=\"mutation\", namespace=\"$namespace\",cluster=~\"^$Account$\"}[$__rate_interval])) by (le, operationName)) > 0",
     "legendFormat": "{{ operationName }}"
    }
   ]
  },
  {
   "title": "Query field duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile/100, sum(irate(apollo_query_field_resolution_duration_bucket{namespace=\"$namespace\",cluster=~\"^$Account$\"}[$__rate_interval])) by (le, operationName, fieldName, returnType)) > 0.001",
     "legendFormat": "op: {{ operationName }} field: {{ fieldName }} return:  {{ returnType }}"
    }
   ]
  },
  {
   "title": "Query executions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(irate(apollo_query_execution_started{namespace=\"$namespace\",cluster=~\"^$Account$\"}[$__rate_interval])) by (operationName) > 0",
     "legendFormat": "{{ operationName }}"
    }
   ]
  },
  {
   "title": "Query failures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(irate(apollo_query_failed{namespace=\"$namespace\",cluster=~\"^$Account$\"}[$__rate_interval])) by (operation, operationName) > 0",
     "legendFormat": "[{{ operation }}] {{ operationName }}"
    },
    {
     "expr": "sum(irate(apollo_query_validation_failed{namespace=\"$namespace\",cluster=~\"^$Account$\"}[$__rate_interval])) by (operationName) > 0",
     "legendFormat": "[validation] {{ operationName }}"
    },
    {
     "expr": "sum(irate(apollo_query_execution_failed{namespace=\"$namespace\",cluster=~\"^$Account$\"}[$__rate_interval])) by (operationName) > 0",
     "legendFormat": "[execution] {{ operationName }}"
    }
   ]
  }
 ]
}