{
 "title": "Application dashboard",
 "tags": [ "developer" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "label": "Account", "query": { "query": "label_values(cluster)" } },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(istio_agent_go_info{cluster=~\"$Account\"}, pod_name)"
    }
   },
   {
    "name": "jobs",
    "query": {
     "query": "label_values(kube_job_info{namespace=\"$namespace\",cluster=~\"$Account\"}, job_name)"
    }
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_status_ready{cluster=~\"$Account\"}, namespace)"
    }
   },
   {
    "name": "custom_interval",
    "label": "Interval",
    "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{workload_type=\"deployment\", namespace=~\"$namespace\",cluster=~\"$Account\"}, workload)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "P50 : 50,P95 : 95,P99 : 99" },
   {
    "name": "function",
    "label": "Output mode",
    "query": "per second : irate,per interval : increase"
   },
   { "name": "resource_group", "label": "Resource group", "query": "namespace,pod,container,node" },
   {
    "name": "istio_metrics_group",
    "label": "Istio metrics group",
    "query": "response code : response_code,response flags : response_flags,request method : request_method,request host : request_host, source workload : source_workload"
   },
   {
    "name": "load_balancer",
    "label": "load_balancer",
    "query": {
     "query": "label_values(aws_applicationelb_target_response_time_average{cluster=~\"$Account\"},load_balancer)"
    }
   },
   {
    "name": "db_instance",
    "label": "db_instance",
    "query": {
     "query": "label_values(mysql_up{cluster=\"$Account\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "round(sum($function(istio_requests_total{destination_workload=~\"$workload\", namespace=~\"$namespace\",reporter=\"destination\",cluster=~\"$Account\"}[$custom_interval])), 0.001)",
     "legendFormat": "Istio"
    },
    {
     "expr": "sum($function(haproxy_backend_http_requests_total{proxy=\"$namespace\",cluster=~\"$Account\"}[$custom_interval]))",
     "legendFormat": "HAProxy"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "round(sum($function(istio_requests_total{destination_workload=~\"$workload\", namespace=~\"$namespace\",reporter=\"destination\",response_code=~\"5.*\",cluster=~\"$Account\"}[$custom_interval])), 0.001)",
     "legendFormat": "[5xx] Istio"
    },
    {
     "expr": "sum($function(istio_requests_total{destination_workload=~\"$workload\", namespace=~\"$namespace\",reporter=\"destination\", response_code=~\"4.*\",cluster=~\"$Account\"}[$custom_interval]))",
     "legendFormat": "[4xx] Istio"
    },
    {
     "expr": "sum($function(haproxy_backend_http_responses_total{proxy=~\"$namespace\", code=~\"5.*\",cluster=~\"$Account\"}[$custom_interval]))",
     "legendFormat": "[5xx] HAProxy"
    },
    {
     "expr": "sum($function(haproxy_backend_http_responses_total{proxy=~\"$namespace\", code=~\"4.*\",cluster=~\"$Account\"}[$custom_interval]))",
     "legendFormat": "[4xx] HAProxy"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(histogram_quantile($percentile/100, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\",response_code!=\"101\",cluster=~\"$Account\"}[$__rate_interval])) by (le)) / 1000) or histogram_quantile($percentile/100, sum(rate(istio_request_duration_seconds_bucket{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\",response_code!=\"101\",cluster=~\"$Account\"}[$__rate_interval])) by (le))",
     "legendFormat": "[P$percentile] Istio"
    },
    {
     "expr": "avg(aws_applicationelb_target_response_time_average{load_balancer=\"$load_balancer\",cluster=~\"$Account\"}) by (load_balancer)",
     "legendFormat": "[avg] ALB target response time - {{load_balancer}} "
    }
   ]
  },
  {
   "title": "DB Status",
   "type": "stat",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(sum(application_health{namespace=\"$namespace\",pod=~\"$workload\",cluster=~\"^$Account$\"}) by (component,operation) - count(application_health{namespace=\"$namespace\",pod=~\"$workload\",cluster=~\"^$Account$\"}) by (component, operation))",
     "legendFormat": "[{{ operation }}] {{ component }}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(apollo_query_failed{namespace=\"$namespace\", operation=\"query\",cluster=~\"$Account\"}[$__rate_interval]))",
     "legendFormat": "Query 5xx"
    },
    {
     "expr": "sum(irate(apollo_query_execution_started{namespace=\"$namespace\",cluster=~\"$Account\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(irate(apollo_query_failed{namespace=\"$namespace\", operation=\"mutation\",cluster=~\"$Account\"}[$__rate_interval]))",
     "legendFormat": "Mutation 5xx"
    },
    {
     "expr": "sum(irate(apollo_query_validation_failed{namespace=\"$namespace\",cluster=~\"$Account\"}[$__rate_interval]))",
     "legendFormat": "Validation 5xx"
    },
    {
     "expr": "sum(irate(apollo_query_execution_failed{namespace=\"$namespace\",cluster=~\"$Account\"}[$__rate_interval]))",
     "legendFormat": "Execution 5xx"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum(rate(istio_requests_total{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\", response_code=~\"5.*\",cluster=~\"$Account\"}[$__rate_interval])) / sum(rate(istio_requests_total{namespace=\"$namespace\",reporter=\"destination\",cluster=~\"$Account\"}[$__rate_interval])))",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Error budget (99.8%)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(istio_requests_total{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\", response_code=~\"5.*\",cluster=~\"$Account\"}[$__range])) / sum(increase(istio_requests_total{namespace=\"$namespace\",reporter=\"destination\",cluster=~\"$Account\"}[$__range]))) * 500",
     "legendFormat": "Used"
    },
    {
     "expr": "(0.002 - (sum(increase(istio_requests_total{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\", response_code=~\"5.*\",cluster=~\"$Account\"}[$__range])) / sum(increase(istio_requests_total{namespace=\"$namespace\",reporter=\"destination\",cluster=~\"$Account\"}[$__range])))) * 500",
     "legendFormat": "Left"
    }
   ]
  },
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packages installed",
     "type": "table",
     "description": "@ekd/prometheus-metrics >= 1.3.1 / @ekd/graphql-core >= 2.17.0",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(npm_packages_installed{namespace=~\"$namespace\", pod=~\"$workload.*\",cluster=~\"$Account\"} > 0) by (package_name, package_type, package_version)"
      }
     ]
    },
    {
     "title": "Current images",
     "type": "table",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",cluster=~\"$Account\"}) by (pod, container, image)"
      }
     ]
    },
    {
     "title": "Status history",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "abs(sum(application_health{namespace=\"$namespace\",pod=~\"$workload\",cluster=~\"$Account\"}) by (component,operation) - count(application_health{namespace=\"$namespace\",pod=~\"$workload\",cluster=~\"$Account\"}) by (component, operation))",
       "legendFormat": "[{{ operation }}] {{ component }}"
      }
     ]
    },
    {
     "title": "Image history",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{namespace=\"$namespace\",cluster=~\"$Account\"}) by (image)",
       "legendFormat": "{{ image }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last terminating containers",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",cluster=~\"$Account\"} > 0"
      }
     ]
    },
    {
     "title": "Last waiting containers",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\",cluster=~\"$Account\"} > 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Cronjobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods",
     "type": "state-timeline",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"Job\"}) by (node)",
       "legendFormat": "{{ node }} {{ service }}"
      }
     ]
    },
    {
     "title": "Running jobs",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"}) by (job_name)",
       "legendFormat": "{{ job_name }}"
      }
     ]
    },
    {
     "title": "Cronjobs",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "kube_cronjob_info{namespace=\"$namespace\"}"
      },
      {
       "expr": "sum(kube_cronjob_created{namespace=\"$namespace\"}) by (cronjob) * 1000"
      },
      {
       "expr": "sum(kube_cronjob_next_schedule_time{namespace=\"$namespace\"}) by (cronjob) * 1000"
      },
      {
       "expr": "(sum(kube_cronjob_status_active{namespace=\"$namespace\"}) by (cronjob)) + (sum(kube_cronjob_spec_suspend{namespace=\"$namespace\"}) by (cronjob) * 2)"
      },
      {
       "expr": "sum(kube_cronjob_status_last_schedule_time{namespace=\"$namespace\"}) by (cronjob) * 1000"
      }
     ]
    },
    {
     "title": "Jobs",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "kube_job_info{namespace=\"$namespace\"}"
      },
      {
       "expr": "sum(kube_job_created{namespace=\"$namespace\"}) by (job_name) * 1000"
      },
      {
       "expr": "(sum(kube_job_status_active{namespace=\"$namespace\"}) by (job_name)) + (sum(kube_job_status_failed{namespace=\"$namespace\"}) by (job_name) * 2) + (sum(kube_job_status_succeeded{namespace=\"$namespace\"}) by (job_name) * 3)"
      },
      {
       "expr": "sum(kube_pod_container_info{namespace=\"$namespace\",pod=~\"$jobs.*\"}) by (pod, image)"
      }
     ]
    }
   ]
  },
  {
   "title": "Public traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "AWS ALB response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(aws_applicationelb_target_response_time_average{load_balancer=~\"$load_balancer\",cluster=~\"$Account\"})",
       "legendFormat": "Response"
      }
     ]
    },
    {
     "title": "Error ratio (5xx)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(aws_applicationelb_httpcode_elb_5_xx_count_sum{load_balancer=\"$load_balancer\", cluster=~\"^$Account$\"}[$__rate_interval])) by (load_balancer)/ sum(rate(aws_applicationelb_request_count_sum{load_balancer=\"$load_balancer\", cluster=~\"^$Account$\"}[$__rate_interval])) by (load_balancer)",
       "legendFormat": "{{load_balancer}}"
      }
     ]
    },
    {
     "title": "Requests by response code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "sum(rate(aws_applicationelb_request_count_sum{load_balancer=\"$load_balancer\",cluster=~\"$Account\"}[$__rate_interval]))",
       "legendFormat": "Total requests"
      },
      {
       "expr": "sum(rate(aws_applicationelb_httpcode_target_2_xx_count_sum{load_balancer=\"$load_balancer\",cluster=~\"$Account\"}[$__rate_interval]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(aws_applicationelb_httpcode_target_3_xx_count_sum{load_balancer=\"$load_balancer\",cluster=~\"$Account\"}[$__rate_interval]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(rate(aws_applicationelb_httpcode_target_4_xx_count_sum{load_balancer=\"$load_balancer\",cluster=~\"$Account\"}[$__rate_interval]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(rate(aws_applicationelb_httpcode_target_5_xx_count_sum{load_balancer=\"$load_balancer\",cluster=~\"$Account\"}[$__rate_interval]))",
       "legendFormat": "5xx"
      }
     ]
    }
   ]
  },
  {
   "title": "Istio incoming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Succeeding Requests by Source And Response Code",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{response_code=~\"(1|2|3).*\", response_flags=\"-\", destination_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"destination\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (source_workload, source_workload_namespace, response_code, response_flags), 0.001) > 0",
       "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} {{ response_flags }}"
      }
     ]
    },
    {
     "title": "Failing Requests by Source And Response Code",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{response_code!~\"(1|2|3).*\", destination_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"destination\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (source_workload, source_workload_namespace, response_code, response_flags), 0.001) > 0",
       "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} {{ response_flags }}"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{response_code=\"1.*\", response_flags!=\"-\", destination_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"destination\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (source_workload, source_workload_namespace, response_code, response_flags), 0.001) > 0",
       "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} {{ response_flags }}"
      }
     ]
    },
    {
     "title": "Average Request Duration by metrics group ($istio_metrics_group)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum(irate(istio_request_duration_milliseconds_sum{destination_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"destination\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by ($istio_metrics_group) / sum(irate(istio_request_duration_milliseconds_count{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by ($istio_metrics_group)) / 1000",
       "legendFormat": "{{ $istio_metrics_group }}"
      }
     ]
    },
    {
     "title": "Requests by Response Code and Flags",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"destination\",cluster=~\"^$Account$\"}[$__rate_interval])) by (response_code, response_flags)",
       "legendFormat": "{{ response_code }} {{ response_flags }}"
      }
     ]
    },
    {
     "title": "Response time by metrics group ($istio_metrics_group)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(histogram_quantile($percentile/100, sum(rate(istio_request_duration_milliseconds_bucket{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (le, $istio_metrics_group)) / 1000) or histogram_quantile($percentile/100, sum(rate(istio_request_duration_seconds_bucket{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (le, $istio_metrics_group))",
       "legendFormat": "P$percentile - {{ $istio_metrics_group }}"
      }
     ]
    },
    {
     "title": "Requests by metrics group ($istio_metrics_group)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"destination\", destination_service!~\".*15020\", request_host!~\".*5000\",cluster=~\"^$Account$\"}[$__rate_interval])) by ($istio_metrics_group)",
       "legendFormat": "{{ $istio_metrics_group }}"
      }
     ]
    },
    {
     "title": "Networking",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 102 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(envoy_cluster_upstream_rq_retry{cluster=~\"^$Account$\"}[$__rate_interval]))",
       "legendFormat": "Retries"
      },
      {
       "expr": "sum(irate(istio_requests_total{destination_workload=~\"$workload\", namespace=\"$namespace\", response_flags=~\".*UO.*\",cluster=~\"^$Account$\"}[$__rate_interval]))",
       "legendFormat": "Circuit breaks"
      }
     ]
    }
   ]
  },
  {
   "title": "Istio outgoing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Succeeding Outgoing Requests by Destination And Response Code",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "round(sum(rate(istio_requests_total{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"source\", response_code!~\"(4|5).*\", response_flags=\"-\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service, response_flags, response_code), 0.001) > 0",
       "legendFormat": "{{ destination_service }} : {{ response_code }} {{ response_flags }}"
      },
      {
       "expr": "round(sum(rate(istio_tcp_connections_opened_total{namespace=\"$namespace\", response_flags=\"-\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service, response_flags), 0.001) > 0",
       "legendFormat": "{{ destination_service }}"
      }
     ]
    },
    {
     "title": "Failing Outgoing Requests by Destination And Response Code",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "round(sum(rate(istio_requests_total{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"source\", response_code=~\"(4|5).*\", response_flags=\"-\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service, response_flags, response_code), 0.001) > 0",
       "legendFormat": "{{ destination_service }} : {{ response_code }}  {{ response_flags }}"
      },
      {
       "expr": "round(sum(rate(istio_tcp_connections_opened_total{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"source\", response_flags!=\"-\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service, response_flags, response_code), 0.001) > 0",
       "legendFormat": "{{ destination_service }} : {{ response_code }}"
      },
      {
       "expr": "round(sum(irate(istio_requests_total{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"source\", response_flags!=\"-\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service, response_flags, response_code), 0.001) > 0",
       "legendFormat": "{{ destination_service }} : {{ response_code }}  {{ response_flags }}"
      }
     ]
    },
    {
     "title": "Outgoing Request Duration by Destination",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(histogram_quantile($percentile/100, sum(irate(istio_request_duration_milliseconds_bucket{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",reporter=\"source\",response_code!=\"101\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service, le)) / 1000) or histogram_quantile($percentile/100, sum(irate(istio_request_duration_seconds_bucket{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",reporter=\"source\",response_code!=\"101\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service, le))",
       "legendFormat": "{{ destination_service }} P$percentile"
      }
     ]
    },
    {
     "title": "Outgoing Success Rate (non-5xx responses) By Destination",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(istio_requests_total{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",reporter=\"source\", response_code!~\"5.*\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service) / sum(irate(istio_requests_total{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",reporter=\"source\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service)",
       "legendFormat": "{{ destination_service }}"
      },
      {
       "expr": "sum(irate(istio_tcp_connections_opened_total{response_flags=\"-\", source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"source\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service) / sum(irate(istio_tcp_connections_opened_total{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\", namespace=\"$namespace\", reporter=\"source\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service)",
       "legendFormat": "{{ destination_service }}"
      }
     ]
    },
    {
     "title": "Outgoing Request Duration by Destination (average)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum(irate(istio_request_duration_milliseconds_sum{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",reporter=\"source\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service) / sum(irate(istio_request_duration_milliseconds_count{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",reporter=\"source\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service)) / 1000 > 0",
       "legendFormat": "{{ destination_service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{namespace=\"$namespace\",pod=~\"$workload.*\",cluster=~\"^$Account$\"}) by (container)",
       "legendFormat": "[ready] {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_status_running{namespace=\"$namespace\",pod=~\"$workload.*\",cluster=~\"^$Account$\"}) by (container)",
       "legendFormat": "[running] {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\",pod=~\"$workload.*\",cluster=~\"^$Account$\"}) by (container,reason) > 0",
       "legendFormat": "[terminated] {{ container }} - {{ reason }}"
      },
      {
       "expr": "sum(kube_pod_container_status_waiting_reason{namespace=\"$namespace\",pod=~\"$workload.*\",cluster=~\"^$Account$\"}) by (container,reason) > 0",
       "legendFormat": "[waiting] {{ container }} - {{ reason }}"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$workload.*\",cluster=~\"^$Account$\"}",
       "legendFormat": "[max] {{ horizontalpodautoscaler }}"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$workload.*\",cluster=~\"^$Account$\"}",
       "legendFormat": "[min] {{ horizontalpodautoscaler }}"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$workload.*\",cluster=~\"^$Account$\"}",
       "legendFormat": "[current] {{ horizontalpodautoscaler }}"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=\"$namespace\",horizontalpodautoscaler=~\"$workload.*\",cluster=~\"^$Account$\"}",
       "legendFormat": "[desired] {{ horizontalpodautoscaler }}"
      }
     ]
    },
    {
     "title": "Autoscaler",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(kube_horizontalpodautoscaler_status_condition{namespace=\"$namespace\",cluster=~\"^$Account$\"}[$__rate_interval])) by (condition)",
       "legendFormat": "[{{ condition }}] {{ horizontalpodautoscaler }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources (selected group - $resource_group)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$workload.*\", namespace=~\"$namespace\",cluster=~\"^$Account$\"}) by ($resource_group)",
       "legendFormat": "Usage - {{ $resource_group }}"
      },
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"$workload.*\", namespace=~\"$namespace\",image!=\"\", container!=\"POD\",cluster=~\"^$Account$\"}[$__rate_interval])) by ($resource_group)",
       "legendFormat": "Throttled - {{ $resource_group }}"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$workload.*\", namespace=~\"$namespace\",cluster=~\"^$Account$\"}) by ($resource_group) / sum(kube_pod_container_resource_limits{pod=~\"$workload.*\", resource=\"cpu\",namespace=~\"$namespace\",cluster=~\"^$Account$\"}) by ($resource_group)",
       "legendFormat": "Utilization - {{ $resource_group }}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{pod=~\"$workload.*\", namespace=~\"$namespace\",container!=\"POD\",container!=\"\",cluster=~\"^$Account$\"}) by ($resource_group)",
       "legendFormat": "Usage (RSS) - {{ $resource_group }}"
      },
      {
       "expr": "sum(container_memory_rss{pod=~\"$workload.*\", namespace=~\"$namespace\",container!=\"POD\",container!=\"\",cluster=~\"^$Account$\"}) by ($resource_group) / sum(kube_pod_container_resource_limits{pod=~\"$workload.*\", resource=\"memory\",namespace=~\"$namespace\",cluster=~\"^$Account$\"}) by ($resource_group)",
       "legendFormat": "Utilization - {{ $resource_group }}"
      }
     ]
    },
    {
     "title": "CPU limit",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{pod=~\"$workload.*\", resource=\"cpu\",namespace=~\"$namespace\",cluster=~\"^$Account$\"}) by ($resource_group)",
       "legendFormat": "{{ $resource_group }}"
      }
     ]
    },
    {
     "title": "Memory limit",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{pod=~\"$workload.*\", resource=\"memory\",namespace=~\"$namespace\",cluster=~\"^$Account$\"}) by ($resource_group)",
       "legendFormat": "{{ $resource_group }}"
      }
     ]
    },
    {
     "title": "CPU requests",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{pod=~\"$workload.*\", resource=\"cpu\",namespace=~\"$namespace\",cluster=~\"^$Account$\"}) by ($resource_group)",
       "legendFormat": "{{ $resource_group }}"
      }
     ]
    },
    {
     "title": "Memory requests",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{pod=~\"$workload.*\", resource=\"memory\",namespace=~\"$namespace\",cluster=~\"^$Account$\"}) by ($resource_group)",
       "legendFormat": "{{ $resource_group }}"
      }
     ]
    },
    {
     "title": "Max usage in time range",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "targets": [
      {
       "expr": "sum(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$workload.*\", namespace=~\"$namespace\",cluster=~\"^$Account$\"}[$__range])) by ($resource_group)",
       "legendFormat": "Usage - {{ $resource_group }}"
      },
      {
       "expr": "sum(max_over_time(container_memory_rss{pod=~\"$workload.*\", namespace=~\"$namespace\",container!=\"POD\",container!=\"\",cluster=~\"^$Account$\"}[$__range])) by ($resource_group)",
       "legendFormat": "Usage - {{ $resource_group }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 113 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"$namespace\", pod=~\"$workload.*\",cluster=~\"^$Account$\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Error",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 113 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting_reason{namespace=~\"$namespace\", pod=~\"$workload.*\",cluster=~\"^$Account$\"} > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unready",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_container_status_ready{namespace=~\"$namespace\", pod=~\"$workload.*\",cluster=~\"^$Account$\"} == 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods (without jobs)",
     "type": "state-timeline",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 120 },
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace=~\"$namespace\", created_by_kind=~\"DaemonSet|ReplicaSet\",cluster=~\"^$Account$\"}) by (node)",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Request Size By Source",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile/100, sum(irate(istio_request_bytes_bucket{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\",cluster=~\"^$Account$\"}[$__rate_interval])) by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P$percentile"
      }
     ]
    },
    {
     "title": "Incoming Response Size By Source",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile/100, sum(irate(istio_response_bytes_bucket{destination_workload=~\"$workload\", namespace=\"$namespace\",reporter=\"destination\",cluster=~\"^$Account$\"}[$__rate_interval])) by (source_workload, source_workload_namespace, le))",
       "legendFormat": "{{source_workload}}.{{source_workload_namespace}}  P$percentile"
      }
     ]
    },
    {
     "title": "Outgoing Request Size By Destination",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile/100, sum(irate(istio_request_bytes_bucket{source_workload_namespace=~\"$namespace\",source_workload=~\"$workload\",reporter=\"source\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service, le))",
       "legendFormat": "{{ destination_service }} P$percentile"
      }
     ]
    },
    {
     "title": "Outgoing Response Size By Destination",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile/100, sum(irate(istio_response_bytes_bucket{source_workload_namespace=~\"$namespace\", source_workload=~\"$workload\",reporter=\"source\", destination_service!~\".*15020\",cluster=~\"^$Account$\"}[$__rate_interval])) by (destination_service, le))",
       "legendFormat": "{{ destination_service }} P$percentile"
      }
     ]
    }
   ]
  }
 ]
}