{
 "title": "Error budgets",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account", "label": "Account", "query": { "query": "label_values(cluster)" } },
   { "name": "datasource", "label": "Country", "query": "prometheus" },
   {
    "name": "services",
    "label": "Services",
    "query": {
     "query": "label_values(eg:istio_workload_p95_7d{cluster=~\"^$Account$\"}, destination_workload)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime statistics",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eg:istio_workload_requests_increase7d:5xx{destination_workload=~\"$services\",cluster=~\"^$Account$\"}"
    },
    {
     "expr": "eg:istio_workload_requests_increase7d{destination_workload=~\"$services\",cluster=~\"^$Account$\"}"
    },
    {
     "expr": "eg:istio_workload_p95_7d{destination_workload=~\"$services\",cluster=~\"^$Account$\"}"
    },
    {
     "expr": "eg:istio_workload_requests_increase7d:5xx{destination_workload=~\"$services\",cluster=~\"^$Account$\"} offset 7d"
    },
    {
     "expr": "eg:istio_workload_requests_increase7d{destination_workload=~\"$services\",cluster=~\"^$Account$\"} offset 7d"
    },
    {
     "expr": "eg:istio_workload_p95_7d{destination_workload=~\"$services\",cluster=~\"^$Account$\"} offset 7d"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - (eg:istio_workload_requests_increase1h:5xx{destination_workload=~\"$services\",cluster=~\"^$Account$\"} / eg:istio_workload_requests_increase1h{destination_workload=~\"$services\",cluster=~\"^$Account$\"}))",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
    }
   ]
  },
  {
   "title": "Errors (1h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "eg:istio_workload_requests_increase1h:5xx{destination_workload=~\"$services\",cluster=~\"^$Account$\"}",
     "legendFormat": "{{ destination_workload_namespace }} - {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "P95 (1h)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "eg:istio_workload_p95_histogram1h{destination_workload=~\"$services\",cluster=~\"^$Account$\"}",
     "legendFormat": "{{ destination_workload_namespace }} - {{ destination_workload }}"
    }
   ]
  },
  {
   "title": "P95 (7 days)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "eg:istio_workload_p95_7d{destination_workload=~\"$services\",cluster=~\"^$Account$\"}",
     "legendFormat": "{{destination_workload}}"
    }
   ]
  }
 ]
}