installProviderConfig: true

global:
  google:
    projectID: ""

  deploymentRuntimeConfig:
    googleServiceAccount: ""

  registry: '{{ .toptout.gar-proxy.hub_registry | "docker.io" }}'

  extraProviders: []
