installProviderConfig: true

global:
  google:
    projectID: ""

  deploymentRuntimeConfig:
    googleServiceAccount: ""
    serviceAccountName: crossplane

  registry: docker.io

  extraProviders: []
