global:
  oracle:
    kubernetesServiceIp: "{{ .toutput.oke.kubernetes_service_ip }}"

logs:
  networkPolicy:
    egress:
      - ports:
          - port: 53
            protocol: UDP
          - port: 53
            protocol: TCP
        to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kube-system
      - ports:
          - port: 80
            protocol: TCP
          - port: 8080
            protocol: TCP
        to:
          - namespaceSelector: {}
            podSelector:
              matchLabels:
                app.kubernetes.io/name: loki
                app.kubernetes.io/component: gateway
      - ports:
          - port: 443
            protocol: TCP
        to:
          - ipBlock:
              cidr: "{{ .toutput.oke.kubernetes_service_ip }}/32"
