node-agent:
  image:
    registry: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}'
  configReloader:
    image:
      registry: '{{ .toptout.ecr-proxy.quay_registry | "quay.io" }}'
cluster-metrics:
  image:
    registry: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}'
  configReloader:
    image:
      registry: '{{ .toptout.ecr-proxy.quay_registry | "quay.io" }}'
