node-agent:
  controller:
    priorityClassName: "{{ .module.name }}"
  logs:
    lokiEndpoint: "http://{{ .tmodule.loki }}-gateway.{{ .tmodule.loki }}/loki/api/v1/push"
  metrics:
    mimirEndpoint: "http://{{ .tmodule.mimir }}-gateway.{{ .tmodule.mimir }}/api/v1/push"
cluster-metrics:
  controller:
    priorityClassName: "{{ .module.name }}"
  mimirEndpoint: "http://{{ .tmodule.mimir }}-gateway.{{ .tmodule.mimir }}/api/v1/push"
