apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: '{{ .Values.gateway.name }}'
  annotations:
    external-dns.alpha.kubernetes.io/ingress: {{ .Release.Namespace }}/{{ .Values.gateway.name }}
spec:
  selector:
    app: '{{ .Values.gateway.name }}'
  servers:
  - hosts:
    - "*"
    port:
      name: http
      number: 80
      protocol: HTTP
