name: PR modules/aws

on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/aws/**'
  workflow_dispatch:

jobs:
  build:
    name: PR modules/aws
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        base_sha: ${{ github.event.pull_request.base.sha }}
        sha: ${{ github.event.pull_request.head.sha }}
    
    - name: Run tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
        PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        ENTIGO_INFRALIB_DESTROY: true
      run: | 
        echo "Changed modules:"
        for module in $(for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file" | grep "modules/aws" | cut -d'/' -f1-3
        done | sort -u )
        do
          ${module}/test.sh
          if [ $? -ne 0 ]
          then
            echo "Failed ${module}"
            exit 2
          fi
        done

