name: PR modules/k8s/cluster-autoscaler

on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/k8s/cluster-autoscaler/**'
  workflow_dispatch:

jobs:
  build:
    name: Test modules/k8s/cluster-autoscaler
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
        GOOGLE_ZONE:  ${{ secrets.GOOGLE_ZONE }}
        GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
        PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        ENTIGO_INFRALIB_DESTROY: true
      run: |
        modules/k8s/cluster-autoscaler/test.sh

