name: PR modules/k8s/crossplane-google

on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/k8s/crossplane-google/**'
  workflow_dispatch:

jobs:
  build:
    name: Test modules/k8s/crossplane-google
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
        PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        ENTIGO_INFRALIB_DESTROY: false
      run: |
        modules/k8s/crossplane-google/test.sh

