name: Test modules/aws/eks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/aws/eks/**'
jobs:
  build:
    name: Test modules/aws/eks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and run Docker image
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
        ENTIGO_INFRALIB_DESTROY: true
      run: |
        modules/aws/eks/test.sh

