name: Update modules/aws/eks

on:
  push:
    branches:
      - main
    paths:
      - 'modules/aws/eks/**'
  workflow_dispatch:

jobs:
  build:
    name: Test modules/aws/eks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and run Docker image
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
        ENTIGO_INFRALIB_DESTROY: false
      run: |
        modules/aws/eks/test.sh
    - name: Slack success
      uses: rtCamp/action-slack-notify@v2
      with:
        status: 'Success'
        message: 'Updated modules/aws/eks on main'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    - name: Slack failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      with:
        status: 'Failed'
        message: 'Failed to update modules/aws/eks on main'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
