name: Nuke

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  nuke:
    name: Nuke AWS account
    runs-on: ubuntu-latest
    steps:
    - name: Slack Started Message
      if: github.event_name != 'schedule'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#EBEB00'
        SLACK_MESSAGE: 'Nuking started of entigo-infralib AWS account!'
        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
        MSG_MINIMAL: actions url,commit
        SLACK_FOOTER: ""
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Nuke entigo-infralib account
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
      run: |
        modules/aws/nuke.sh
        echo "Fake nuke"
    - name: Slack Failed To Nuke Message
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'failure'
        SLACK_MESSAGE: 'Failed to Nuke the entigo-infralib account!'
        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
        SLACK_FOOTER: ""
