name: Nuke

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  nuke:
    name: Nuke AWS account
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Nuke entigo-infralib account
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
      run: |
        modules/aws/nuke.sh
  install_stable:
    name: Install stable release
    needs: nuke
    runs-on: ubuntu-latest
    steps:
    - name: Get latest release
      uses: actions/github-script@v4
      with:
        script: |
          const { data: releases } = await github.repos.listReleases({ owner: context.repo.owner, repo: context.repo.repo });
          const latestRelease = releases[0];
          core.setOutput('release_tag', latestRelease.tag_name);
          core.info('Latest release tag: ' + latestRelease.tag_name);

    - name: Checkout code of latest release
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.get_latest_release.outputs.release_tag }}
    - name: Create resources based on latest release
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
        ENTIGO_INFRALIB_DESTROY: false
      run: |
        modules/aws/vpc/test.sh 
  install_main:
    name: Upgrade stable to main
    needs: install_stable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update resources based on main code
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
        ENTIGO_INFRALIB_DESTROY: false
      run: |
        modules/aws/vpc/test.sh
