name: Nuke

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  nuke_aws:
    name: Nuke AWS account
    runs-on: ubuntu-latest
    steps:
    - name: Slack Started Message
      if: github.event_name != 'schedule'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: '#EBEB00'
        SLACK_MESSAGE: 'Nuking started of entigo-infralib AWS and google accounts!'
        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
        MSG_MINIMAL: actions url,commit
        SLACK_FOOTER: ""
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Nuke entigo-infralib account
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION:  ${{ secrets.AWS_REGION }}
      run: |
        modules/aws/nuke.sh || modules/aws/nuke.sh
    - name: Slack Failed To Nuke Message
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'failure'
        SLACK_MESSAGE: 'Failed to Nuke the entigo-infralib AWS account!'
        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
        SLACK_FOOTER: ""

  nuke_gcp:
    name: Nuke Google project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Nuke entigo-infralib google project
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
        GOOGLE_ZONE:  ${{ secrets.GOOGLE_ZONE }}
        GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        modules/google/nuke.sh || modules/google/nuke.sh
    - name: Slack Failed To Nuke Google Message
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: 'failure'
        SLACK_MESSAGE: 'Failed to Nuke the entigo-infralib google project!'
        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
        SLACK_FOOTER: ""
