argocd:
  global:
    domain: |
      {{ .module.name }}.{{ .toutput.route53.int_domain }}
    image:
      repository: '{{ .toptout.ecr-proxy.quay_registry | "quay.io" }}/argoproj/argocd'
  dex:
    image:
      repository: '{{ .toptout.ecr-proxy.ghcr_registry | "ghcr.io" }}/dexidp/dex'
  redis:
    image:
      repository: '{{ .toptout.ecr-proxy.ecr_registry | "public.ecr.aws" }}/docker/library/redis'
  configs:
    repositories:
      infralib-oci-ecr:
        url: oci://public.ecr.aws/entigolabs/entigo-infralib-release/k8s
        name: infralib-oci-ecr
        type: oci
      infralib-oci-ghcr:
        url: oci://ghcr.io/entigolabs/entigo-infralib-release/k8s
        name: infralib-oci-ghcr
        type: oci

job:
  image: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}/entigolabs/entigo-infralib-kubectl'
