argocd:
  global:
    domain: |
      {{ .module.name }}.{{ .toutput.dns.int_domain }}
    image:
      repository: '{{ .toptout.gar-proxy.quay_registry | "quay.io" }}/argoproj/argocd'
  dex:
    image:
      repository: '{{ .toptout.gar-proxy.ghcr_registry | "ghcr.io" }}/dexidp/dex'
  redis:
    image:
      repository: '{{ .toptout.gar-proxy.ecr_registry | "public.ecr.aws" }}/docker/library/redis'
  configs:
    repositories:
      infralib-oci-ecr:
        url: oci://{{ .toptout.gar-proxy.ecr_registry | "public.ecr.aws" }}/entigolabs/entigo-infralib-release
        name: infralib-oci-ecr
        type: helm
        enableOCI: "true"
      infralib-oci-ghcr:
        url: oci://{{ .toptout.gar-proxy.ghcr_registry | "ghcr.io" }}/entigolabs/entigo-infralib-release
        name: infralib-oci-ghcr
        type: helm
        enableOCI: "true"
job:
  image: '{{ .toptout.gar-proxy.hub_registry | "docker.io" }}/entigolabs/entigo-infralib-kubectl'
