cloudProvider: google

google:
  gateway:
    name: gcp-gateway-external
    namespace: gcp-gateway

argocd:
  configs:
    params:
      server.insecure: true
  server:
    ingress:
      enabled: false
