global:
  cloudProvider: google
  google:
    gateway:
      name: google-gateway-internal
      namespace: google-gateway

argocd:
  configs:
    params:
      server.insecure: false
  server:
    ingress:
      enabled: false
