cloudProvider: google

google:
  gateway:
    name: google-gateway-external
    namespace: google-gateway

argocd:
  configs:
    params:
      server.insecure: true
  server:
    ingress:
      enabled: false
