argocd:
  crds:
    install: true
    keep: true
  global:
    networkPolicy:
      create: true
  server:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 1Gi
    autoscaling:
      enabled: true
      minReplicas: 2  
    config:
      server.rbac.log.enforce.enable: "true"
      admin.enabled: "true"
      exec.enabled: "true"
      url: https://argocd.${domain}
    ingress:
      enabled: true
      annotations: 
        alb.ingress.kubernetes.io/backend-protocol: HTTPS
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
        alb.ingress.kubernetes.io/group.name: internal
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/target-type: ip
      ingressClassName: "alb"
      paths:
      - /
    ingressGrpc:
      enabled: true
      isAWSALB: true
      ingressClassName: "alb"
      awsALB:
        serviceType: ClusterIP
      annotations: 
        alb.ingress.kubernetes.io/backend-protocol: HTTPS
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
        alb.ingress.kubernetes.io/group.name: internal
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/target-type: ip
  dex:
    deploymentAnnotations:
      kube-score/ignore: pod-probes
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
        ephemeral-storage: 20Gi
      requests:
        cpu: 10m
        memory: 32Mi
        ephemeral-storage: 2Gi
        
  redis:
    enabled: true
    deploymentAnnotations:
      kube-score/ignore: pod-probes
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources:
      limits:
        cpu: 1000m
        memory: 128Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 1Gi
        
  redis-ha:
    enabled: false
    redis:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
              - key: tools
                operator: In
                values:
                - "true"
      tolerations:
        - key: "tools"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      resources:
        limits:
          cpu: 1000m
          memory: 128Mi
          ephemeral-storage: 10Gi
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 1Gi
    sentinel:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
              - key: tools
                operator: In
                values:
                - "true"
      tolerations:
        - key: "tools"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      resources:
        limits:
          cpu: 1000m
          memory: 128Mi
          ephemeral-storage: 10Gi
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 1Gi
    haproxy:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
              - key: tools
                operator: In
                values:
                - "true"
      tolerations:
        - key: "tools"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      resources:
        limits:
          cpu: 1000m
          memory: 128Mi
          ephemeral-storage: 10Gi
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 1Gi
        
  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 1Gi
      
  applicationSet:
    replicaCount: 2
    deploymentAnnotations:
      kube-score/ignore: pod-networkpolicy,pod-probes
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 1Gi

  notifications:
    deploymentAnnotations:
      kube-score/ignore: pod-networkpolicy
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources:
      limits:
        cpu: 1000m
        memory: 128Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 100m
        memory: 128Mi
        ephemeral-storage: 1Gi

  controller:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
            - key: tools
              operator: In
              values:
              - "true"
    tolerations:
       - key: "tools"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"
    resources:
      limits:
        cpu: 2000m
        memory: 2048Mi
        ephemeral-storage: 10Gi
      requests:
        cpu: 100m
        memory: 512Mi
        ephemeral-storage: 1Gi
